Repository submariner-io/submariner-operator, pull requests merged in 2019-12, with the labels that each got.

#75 Flip the dataplane default
  pkg/subctl/cmd/deploybroker.go
  scripts/kind-e2e/e2e.sh
Labels: enhancement, subctl

#71 Add licensing information
  LICENSE
  cmd/manager/main.go
  pkg/apis/addtoscheme_submariner_v1alpha1.go
  pkg/apis/apis.go
  pkg/apis/submariner/group.go
  pkg/apis/submariner/v1alpha1/doc.go
  pkg/apis/submariner/v1alpha1/submariner_types.go
  pkg/broker/broker_test_suite.go
  pkg/broker/ensure.go
  pkg/broker/ipsec_psk.go
  pkg/broker/ipsec_psk_test.go
  pkg/broker/namespace.go
  pkg/broker/rbac.go
  pkg/controller/add_submariner.go
  pkg/controller/controller.go
  pkg/controller/submariner/submariner_controller.go
  pkg/controller/submariner/submariner_suite_test.go
  pkg/discovery/network/canal.go
  pkg/discovery/network/canal_test.go
  pkg/discovery/network/generic.go
  pkg/discovery/network/generic_test.go
  pkg/discovery/network/network.go
  pkg/discovery/network/network_suite_test.go
  pkg/discovery/network/openshift4.go
  pkg/discovery/network/openshift4_test.go
  pkg/discovery/network/pods.go
  pkg/discovery/network/pods_test.go
  pkg/discovery/network/weavenet.go
  pkg/discovery/network/weavenet_test.go
  pkg/engine/crds.go
  pkg/subctl/cmd/deploybroker.go
  pkg/subctl/cmd/info.go
  pkg/subctl/cmd/join.go
  pkg/subctl/cmd/root.go
  pkg/subctl/datafile/datafile.go
  pkg/subctl/datafile/datafile_test.go
  pkg/subctl/main.go
  pkg/subctl/operator/deploy/ensure.go
  pkg/subctl/operator/deploy/namespace.go
  pkg/subctl/operator/install/crds/crds_test.go
  pkg/subctl/operator/install/crds/ensure.go
  pkg/subctl/operator/install/deployment/ensure.go
  pkg/subctl/operator/install/embeddedyamls/generators/yamls2go.go
  pkg/subctl/operator/install/embeddedyamls/unmarshal.go
  pkg/subctl/operator/install/ensure.go
  pkg/subctl/operator/install/namespace/ensure.go
  pkg/subctl/operator/install/scc/ensure.go
  pkg/subctl/operator/install/serviceaccount/ensure.go
  tools.go
  version/version.go
Labels: documentation

#109 Only run travis on master branch and PRs
  .travis.yml
Labels: automation
