Repository submariner-io/submariner-operator, pull requests merged in 2020-09, with the labels that each got.

#689 Support detecting all networks in OpenShift
  deploy/cluster_role.yaml
  pkg/discovery/network/openshift4.go
  pkg/discovery/network/openshift4_test.go
Labels: OVN

#708 Delete existing CRs when joining
  pkg/subctl/operator/submarinercr/ensure.go
Labels: bug

#714 Fix subctl verify/benchmark with tainted nodes
  go.mod
  go.sum
Labels: bug

#627 Check Prometheus metrics
  .github/workflows/prometheus.yaml
Labels: check-prometheus
