Repository submariner-io/submariner-operator, pull requests merged in 2020-02, with the labels that each got.

#198 Fix panic in getPodCIDR
  pkg/subctl/cmd/join.go
Labels: backport

#205 Make travis also build release branches
  .travis.yml
Labels: automation, backport

#189 operator: Spec changes for globalnet
  deploy/crds/submariner.io_submariners_crd.yaml
  pkg/apis/submariner/v1alpha1/submariner_types.go
  pkg/apis/submariner/v1alpha1/zz_generated.openapi.go
  pkg/controller/submariner/submariner_controller.go
  pkg/controller/submariner/submariner_controller_test.go
Labels: globalnet, operator

#199 Clarify message when no node found to label
  pkg/subctl/cmd/root.go
Labels: backport, enhancement

#170 subctl: add globalnet options to deploybroker
  pkg/subctl/cmd/deploybroker.go
  pkg/subctl/datafile/datafile.go
Labels: globalnet, subctl
