Repository submariner-io/submariner-operator, pull requests merged in 2020-03, with the labels that each got.

#218 Don’t set DNS up on broker
  pkg/subctl/lighthouse/deploy/ensure.go
Labels: bug

#219 Implement DaemonSet update in ReconcileSubmariner
  go.mod
  pkg/controller/submariner/submariner_controller.go
  pkg/controller/submariner/submariner_controller_test.go
Labels: enhancement, operator, technical-debt

#234 Run go mod tidy to remove unused dependencies
  go.sum
Labels: dependencies

#238 Add flag to disable the OpenShift CVO
  pkg/versions/versions.go
Labels: enhancement, lighthouse, subctl, technical-debt

#245 Fix issue with wrong token stored in subm file (OpenShift)
  pkg/broker/rbac.go
  pkg/subctl/datafile/datafile_test.go
Labels: bug, subctl

#246 Fix issue with wrong token stored in subm file (OpenShift)
  pkg/broker/rbac.go
  pkg/subctl/datafile/datafile_test.go
Labels: bug

#263 Use context when enabling namespaces
  pkg/subctl/lighthouse/deploy/ensure.go
  pkg/subctl/lighthouse/install/crds/ensure.go
  pkg/subctl/lighthouse/install/ensure.go
  pkg/subctl/operator/kubefed/ensure.go
Labels: lighthouse

#265 Return appropriate err for globalClusterSize
  pkg/subctl/cmd/deploybroker.go
Labels: globalnet

#254 Enable globalnet in e2e and CI
  .travis.yml
  scripts/kind-e2e/e2e.sh
Labels: globalnet
