Repository submariner-io/submariner-operator, pull requests merged in 2020-08, with the labels that each got.

#581 Refactor/improve network discovery error handling
  pkg/discovery/network/canal.go
  pkg/discovery/network/generic.go
  pkg/discovery/network/network.go
  pkg/discovery/network/openshift4.go
  pkg/discovery/network/pods.go
Labels: cncf

#579 Enable unparam unused param linting, fix errors
  .golangci.yml
  pkg/controller/submariner/submariner_networkdiscovery.go
  pkg/subctl/operator/lighthouse/serviceaccount/ensure.go
  pkg/subctl/operator/submarinerop/serviceaccount/ensure.go
Labels: automation, cncf

#585 Enable lll line length linting, fix errors
  .golangci.yml
  cmd/manager/main.go
  pkg/broker/ensure.go
  pkg/controller/servicediscovery/servicediscovery_controller.go
  pkg/controller/submariner/submariner_controller.go
  pkg/controller/submariner/submariner_controller_test.go
  pkg/discovery/network/network.go
  pkg/subctl/cmd/export.go
  pkg/subctl/cmd/show_versions.go
  pkg/subctl/operator/submarinercr/ensure.go
Labels: automation, cncf

#650 Enable gosec linting, fix errors
  .golangci.yml
  pkg/subctl/datafile/datafile.go
  pkg/subctl/datafile/datafile_test.go
Labels: automation, cncf

#647 Add commit message validations
  .github/workflows/gitlint.yaml
  .gitlint
Labels: automation, cncf, documentation

#652 Bump MD link check linter 0.6->1.*
  .github/workflows/md-links-periodic.yml
  .github/workflows/md-links.yml
Labels: automation, cncf, documentation

#654 Add YAML linting, fix errors
  .github/workflows/dco-check.yml
  .github/workflows/e2e.yml
  .github/workflows/gitlint.yml
  .github/workflows/md-links-periodic.yml
  .github/workflows/md-links.yml
  .github/workflows/md-lint.yml
  .github/workflows/release.yml
  .github/workflows/subctl_bin.yml
  .github/workflows/subctl_bleeding_edge.yml
  .github/workflows/validations.yml
  .github/workflows/yaml-lint.yml
  .golangci.yml
  .markdownlint.yml
  .yamllint.yml
  deploy/cluster_role.yaml
  deploy/cluster_role_binding.yaml
  deploy/crds/submariner.io_servicediscoveries_crd.yaml
  deploy/crds/submariner.io_submariners_crd.yaml
  deploy/crds/submariner.io_v1alpha1_servicediscovery_cr.yaml
  deploy/crds/submariner.io_v1alpha1_submariner_cr.yaml
  deploy/lighthouse/cluster_role.yaml
  deploy/lighthouse/cluster_role_binding.yaml
  deploy/lighthouse/crds/multiclusterservices_crd.yaml
  deploy/lighthouse/crds/serviceexport_crd.yaml
  deploy/lighthouse/crds/serviceimport_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  deploy/submariner/globalnet_cluster_role.yaml
  deploy/submariner/globalnet_cluster_role_binding.yaml
Labels: automation, cncf
