Repository submariner-io/submariner-operator, pull requests merged in 2020-11, with the labels that each got.

#784 Add subctl cross-compiling for arm32 (rpi raspbian)
  Makefile
Labels: multiarch

#799 Fix GH issue reporting on flaky test failures
  .github/ISSUE_TEMPLATE/flaky_failure_automated.md
  .github/workflows/flake_finder.yml
Labels: automation

#801 Fix broken link to OpenShift with discovery docs
  README.md
Labels: bug, documentation

#822 Allow multiarch images
  Dockerfile.dapper
Labels: multiarch

#817 Bump create-issue GHA version
  .github/workflows/flake_finder.yml
Labels: automation, dependencies

#837 Run `go mod tidy`
  go.sum
Labels: automation, dependencies

#840 Fix release job, avoid deprecated set-env
  .github/workflows/subctl_bleeding_edge.yml
Labels: automation, dependencies

#800 Add badges for GHA workflows to README
  README.md
Labels: automation, documentation

#869 feat: add image-override flag to subctl command
  pkg/subctl/cmd/join.go
Labels: check-okd-rke

#912 Remove flaky test failure automatic reporting
  .github/ISSUE_TEMPLATE/flaky_failure_automated.md
  .github/workflows/flake_finder.yml
Labels: automation
