Repository submariner-io/submariner-operator, pull requests merged in 2020-04, with the labels that each got.

#294 Deleted unused files
  scripts/kind-e2e/deploy-operator-local.yaml
  scripts/kind-e2e/nginx-federated.sh
  scripts/kind-e2e/operator-csv.yaml
  scripts/kind-e2e/operator-group.yaml
  scripts/kind-e2e/operator-source.yaml
  scripts/kind-e2e/operator-subscription.yaml
Labels: automation

#278 Ensure that update operations are retried
  pkg/subctl/lighthouse/dns/ensure.go
  pkg/subctl/lighthouse/install/crds/ensure.go
  pkg/subctl/lighthouse/install/deployment/ensure.go
  pkg/subctl/operator/common/deployments/utils.go
  pkg/subctl/operator/common/operatorpod/ensure.go
  pkg/subctl/operator/kubefedop/clusterrole/ensure.go
  pkg/subctl/operator/kubefedop/clusterrolebinding/ensure.go
  pkg/subctl/operator/kubefedop/crds/crds_test.go
  pkg/subctl/operator/kubefedop/crds/ensure.go
  pkg/subctl/operator/kubefedop/role/ensure.go
  pkg/subctl/operator/kubefedop/rolebinding/ensure.go
  pkg/subctl/operator/submarinercr/ensure.go
  pkg/subctl/operator/submarinerop/crds/crds_test.go
  pkg/subctl/operator/submarinerop/crds/ensure.go
  pkg/subctl/operator/submarinerop/scc/ensure.go
  pkg/subctl/operator/submarinerop/serviceaccount/ensure.go
  pkg/utils/createorupdate.go
  pkg/utils/createorupdate_test.go
Labels: technical-debt

#317 Don't play with pipefail
  scripts/kind-e2e/e2e.sh
Labels: automation

#315 Remove the status flag from e2e
  .travis.yml
  Makefile
  README.md
  scripts/kind-e2e/README.md
  scripts/kind-e2e/e2e.sh
Labels: automation, shipyard

#339 Use Shipyard's deploy target
  .travis.yml
  Dockerfile.dapper
  Makefile
  README.md
  scripts/kind-e2e/README.md
  scripts/kind-e2e/e2e.sh
  scripts/kind-e2e/lib_operator_verify_subm.sh
  scripts/preload_images
Labels: shipyard
