Repository submariner-io/submariner-operator, pull requests merged in 2020-06, with the labels that each got.

#404 Fix globalCIDR auto-allocation error
  pkg/discovery/globalnet/globalnet.go
Labels: globalnet

#419 Add a script to download and install subctl
  scripts/subctl/getsubctl.sh
Labels: UX

#477 Add DCO signed-off-by GHA validation
  .github/workflows/dco-check.yml
Labels: automation, cncf
