Repository submariner-io/submariner-operator, pull requests merged in 2020-07, with the labels that each got.

#519 Remove the travis CI file
  .travis.yml
Labels: automation

#562 Fix empty globalCidr in submariner-globalnet-info ConfigMap
  pkg/discovery/globalnet/globalnet.go
  pkg/subctl/cmd/join.go
Labels: bug

#567 Set Globalnet_enabled flag in lighthouse agent env
  pkg/controller/servicediscovery/servicediscovery_controller.go
Labels: lighthouse

#573 Add golangci-lint config file, add linters
  .golangci.yml
Labels: automation, cncf

#575 Enable gofmt linter, fix errors
  .golangci.yml
  pkg/broker/rbac.go
Labels: automation, cncf

#577 Add misspell linter, fix errors
  .golangci.yml
  pkg/controller/submariner/submariner_controller.go
Labels: automation, cncf

#578 Enable whitespace linting, fix errors
  .golangci.yml
  pkg/apis/submariner/v1alpha1/submariner_types.go
  pkg/broker/ensure.go
  pkg/broker/rbac.go
  pkg/controller/submariner/submariner_controller.go
  pkg/controller/submariner/submariner_controller_test.go
  pkg/controller/submariner/submariner_networkdiscovery.go
  pkg/discovery/globalnet/globalnet.go
  pkg/discovery/network/canal.go
  pkg/discovery/network/canal_test.go
  pkg/discovery/network/generic.go
  pkg/discovery/network/generic_test.go
  pkg/discovery/network/network.go
  pkg/discovery/network/openshift4.go
  pkg/discovery/network/pods.go
  pkg/discovery/network/weavenet.go
  pkg/subctl/cmd/deploybroker.go
  pkg/subctl/cmd/export.go
  pkg/subctl/cmd/join.go
  pkg/subctl/cmd/root.go
  pkg/subctl/cmd/verify.go
  pkg/subctl/datafile/datafile.go
  pkg/subctl/datafile/ipsec_psk.go
  pkg/subctl/operator/common/deployments/utils.go
  pkg/subctl/operator/common/embeddedyamls/generators/yamls2go.go
  pkg/subctl/operator/common/embeddedyamls/unmarshal.go
  pkg/subctl/operator/common/namespace/ensure.go
  pkg/subctl/operator/common/scc/utils.go
  pkg/subctl/operator/lighthouse/ensure.go
  pkg/subctl/operator/lighthouse/serviceaccount/ensure.go
  pkg/subctl/operator/submarinercr/ensure.go
  pkg/subctl/operator/submarinerop/ensure.go
  pkg/subctl/operator/submarinerop/serviceaccount/ensure.go
  pkg/utils/createorupdate.go
Labels: automation, cncf

#580 Enable maligned memory use linter, fix errors
  .golangci.yml
  pkg/apis/submariner/v1alpha1/servicediscovery_types.go
  pkg/apis/submariner/v1alpha1/submariner_types.go
  pkg/discovery/globalnet/globalnet.go
  pkg/internal/cli/logger.go
Labels: automation, cncf
