Repository submariner-io/submariner-operator, pull requests merged in 2020-12, with the labels that each got.

#913 Fix periodic broken link test issue reporting
  .github/ISSUE_TEMPLATE/broken-link.md
  .github/workflows/periodic.yml
Labels: automation

#902 Reduce flaky test finder frequency
  .github/workflows/flake_finder.yml
Labels: automation

#904 Remove hard-coded override of cable driver flag
  Makefile
  scripts/kind-e2e/lib_operator_verify_subm.sh
Labels: automation

#962 Fix cable driver false test failure
  scripts/kind-e2e/lib_operator_verify_subm.sh
Labels: automation

#964 Fix all broken links
  .markdownlinkcheck.json
  CODE-OF-CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: broken link, documentation

#990 Update gitlint ignore for new Dependabot
  .gitlint
Labels: automation

#1007 Generate the submariners crd again to update the changes for bundle 0.8.0
  bundle/manifests/submariner.io_submariners.yaml
  config/crd/bases/submariner.io_submariners.yaml
  packagemanifests/0.8.0/submariner.io_submariners.yaml
Labels: backport, operator

#1009 Update references to Lighthouse repo
  go.mod
  go.sum
Labels: backport

#1008 Ensure that CRDs are up-to-date
  .github/workflows/linting.yml
Labels: backport

#1001 Detect OVNKubernetes without Cluster Network Operator
  controllers/submariner/netwokplugin_syncer.go
  controllers/submariner/submariner_controller.go
  controllers/submariner/submariner_networkdiscovery.go
  pkg/discovery/network/generic_test.go
  pkg/discovery/network/network.go
  pkg/discovery/network/network_suite_test.go
  pkg/discovery/network/ovnkubernetes.go
  pkg/discovery/network/ovnkubernetes_test.go
Labels: OVN, backport, bug

#994 Add gateway uptime metric
  controllers/submariner/submariner_controller.go
  controllers/submariner/submariner_metrics.go
Labels: metrics

#1012 Add upgrade tests to flake finder
  .github/workflows/flake_finder.yml
  .github/workflows/upgrade-e2e.yml
Labels: automation
