Repository submariner-io/submariner-operator, pull requests merged in 2021-01, with the labels that each got.

#1016 fix(makefile): update embedded-yamls when rbac files change
  Makefile
Labels: bug, operator, subctl

#996 Allow multiple metric test attempts
  .github/workflows/prometheus.yml
Labels: check-prometheus

#1011 Add license headers to Go files
  apis/submariner/v1alpha1/register.go
  apis/submariner/v1alpha1/servicediscovery_types.go
  apis/submariner/v1alpha1/zz_generated.openapi.go
  controllers/helpers/helpers.go
  controllers/servicediscovery/servicediscovery_controller.go
  controllers/servicediscovery/servicediscovery_controller_test.go
  controllers/submariner/netwokplugin_syncer.go
  controllers/submariner/submariner_controller_test.go
  controllers/submariner/submariner_metrics.go
  controllers/submariner/submariner_networkdiscovery.go
  pkg/broker/globalcidr_cm.go
  pkg/discovery/globalnet/globalnet.go
  pkg/discovery/globalnet/globalnet_suite_test.go
  pkg/discovery/globalnet/globalnet_test.go
  pkg/discovery/network/ovnkubernetes.go
  pkg/discovery/network/ovnkubernetes_test.go
  pkg/images/image_parsing_test.go
  pkg/images/images.go
  pkg/lighthouse/crds.go
  pkg/names/names.go
  pkg/subctl/benchmark/latency.go
  pkg/subctl/benchmark/throughput.go
  pkg/subctl/cmd/benchmark.go
  pkg/subctl/cmd/export.go
  pkg/subctl/cmd/show_all.go
  pkg/subctl/cmd/show_connections.go
  pkg/subctl/cmd/show_endpoints.go
  pkg/subctl/cmd/show_gateways.go
  pkg/subctl/cmd/show_networks.go
  pkg/subctl/cmd/show_versions.go
  pkg/subctl/cmd/verify.go
  pkg/subctl/cmd/verify_connectivity.go
  pkg/subctl/datafile/backup.go
  pkg/subctl/operator/common/deployments/utils.go
  pkg/subctl/operator/common/embeddedyamls/generate.go
  pkg/subctl/operator/common/scc/utils.go
  pkg/subctl/operator/lighthouse/scc/ensure.go
  pkg/utils/crds/crdutils.go
  pkg/utils/createorupdate.go
  pkg/utils/createorupdate_test.go
  pkg/version/version.go
  pkg/versions/versions.go
Labels: cncf

#1014 chore: update CSV broken links
  bundle/manifests/submariner.clusterserviceversion.yaml
  config/manifests/bases/submariner.clusterserviceversion.yaml
  packagemanifests/0.8.0/submariner.v0.8.0.clusterserviceversion.yaml
Labels: operator

#1020 Deploy ServiceMonitor for globalnet
  controllers/submariner/submariner_controller.go
Labels: metrics

#1026 Use the PR base branch as reference when linting
  .github/workflows/linting.yml
Labels: backport

#972 Added flag to skip GlobalNet configuration on join.
  pkg/subctl/cmd/join.go
Labels: globalnet, ocs+dedicated, subctl

#1054 AKS: Use coredns-custom configmap for lighthouse
  controllers/servicediscovery/servicediscovery_controller.go
Labels: aks
