Repository submariner-io/submariner-operator, pull requests merged in 2021-09, with the labels that each got.

#1553 Modify AWS GW default image to c5d.large
  pkg/subctl/cmd/cloud/prepare/aws.go
Labels: ready-to-test

#1554 Move gather.go to gather pkg
  pkg/subctl/cmd/gather/cni.go
  pkg/subctl/cmd/gather/connectivity.go
  pkg/subctl/cmd/gather/gather.go
  pkg/subctl/cmd/gather/operator.go
  pkg/subctl/cmd/gather/servicediscovery.go
  pkg/subctl/cmd/gather/summary.go
  pkg/subctl/main.go
Labels: ready-to-test

#1558 build(bundle): use default values
  .github/workflows/periodic.yml
  Makefile
Labels: ready-to-test

#1562 Add .mdignore file, ignore apis/vendor dir
  .mdignore
Labels: automation, ready-to-test

#1563 Mount /lib/modules in gateway containers
  controllers/submariner/gateway_resources.go
Labels: ready-to-test

#1565 Revert "Add .mdignore file, ignore apis/vendor dir"
  .mdignore
Labels: ready-to-test

#1566 Remove non-functional yamllint strict config
  .yamllint.yml
Labels: automation, ready-to-test

#1556 Allow specifying the Go implementation to use
  Makefile
Labels: ready-to-test

#1568 build(bundle): set default values for the bundle channels
  Makefile
Labels: ready-to-test

#1572 Update aws client to pass clientsets to cloud-prepare
  go.mod
  go.sum
  pkg/subctl/cmd/cloud/aws/aws.go
Labels: ready-to-test

#1573 Add the --kubecontext flag to deploy-broker
  pkg/subctl/cmd/deploybroker.go
Labels: ready-to-test

#1575 Enable specifying an empty instanceType for AWS cluster
  pkg/subctl/cmd/cloud/prepare/aws.go
  pkg/subctl/cmd/cloud/prepare/gcp.go
  pkg/subctl/cmd/cloud/prepare/prepare.go
Labels: ready-to-test

#1578 Use devel as subctl default version
  pkg/version/version.go
Labels: ready-to-test

#1579 Fix typo in subctl release GHA file name
  .github/workflows/release_subctl_on_push.yml
Labels: bug, automation, ready-to-test

#1584 Avoid direct error comparisons
  controllers/metrics/metrics.go
  main.go
  pkg/broker/ensure.go
  pkg/metrics/metrics.go
  pkg/subctl/cmd/root.go
  pkg/subctl/cmd/verify.go
Labels: ready-to-test
