Repository submariner-io/submariner-operator, pull requests merged in 2021-08, with the labels that each got.

#1518 Limit cluster-id to 63 chars while joining a cluster
  pkg/subctl/cmd/join.go
Labels: ready-to-test

#1525 Don't run periodic PR dependency checks on forks
  .github/workflows/dependent-issues.yml
Labels: automation, ready-to-test

#1527 Fix YAML linting errors
  .github/dependabot.yml
  .github/workflows/dependent-issues.yml
  .lichen.yaml
  .submarinerbot.yaml
  config/broker/kustomization.yaml
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/samples/kustomization.yaml
  config/samples/submariner_v1alpha1_broker.yaml
Labels: automation, ready-to-test

#1538 Pin Shipyard to v0.10.1
  go.mod
  go.sum
Labels: ready-to-test

#1528 Run Flake Finder twice a day
  .github/workflows/flake_finder.yml
Labels: automation, ready-to-test

#1545 chore: rename bundle 0.10.0 to 0.10.1
  bundle/manifests/submariner.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
  packagemanifests/0.10.1/submariner-gateway_rbac.authorization.k8s.io_v1_clusterrole.yaml
  packagemanifests/0.10.1/submariner-gateway_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  packagemanifests/0.10.1/submariner-gateway_rbac.authorization.k8s.io_v1_role.yaml
  packagemanifests/0.10.1/submariner-gateway_rbac.authorization.k8s.io_v1_rolebinding.yaml
  packagemanifests/0.10.1/submariner-gateway_v1_serviceaccount.yaml
  packagemanifests/0.10.1/submariner-globalnet_rbac.authorization.k8s.io_v1_clusterrole.yaml
  packagemanifests/0.10.1/submariner-globalnet_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  packagemanifests/0.10.1/submariner-globalnet_rbac.authorization.k8s.io_v1_role.yaml
  packagemanifests/0.10.1/submariner-globalnet_rbac.authorization.k8s.io_v1_rolebinding.yaml
  packagemanifests/0.10.1/submariner-globalnet_v1_serviceaccount.yaml
  packagemanifests/0.10.1/submariner-lighthouse-agent_rbac.authorization.k8s.io_v1_clusterrole.yaml
  packagemanifests/0.10.1/submariner-lighthouse-agent_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  packagemanifests/0.10.1/submariner-lighthouse-agent_v1_serviceaccount.yaml
  packagemanifests/0.10.1/submariner-lighthouse-coredns_rbac.authorization.k8s.io_v1_clusterrole.yaml
  packagemanifests/0.10.1/submariner-lighthouse-coredns_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  packagemanifests/0.10.1/submariner-lighthouse-coredns_v1_serviceaccount.yaml
  packagemanifests/0.10.1/submariner-networkplugin-syncer_rbac.authorization.k8s.io_v1_clusterrole.yaml
  packagemanifests/0.10.1/submariner-networkplugin-syncer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  packagemanifests/0.10.1/submariner-networkplugin-syncer_v1_serviceaccount.yaml
  packagemanifests/0.10.1/submariner-operator_v1_serviceaccount.yaml
  packagemanifests/0.10.1/submariner-routeagent_rbac.authorization.k8s.io_v1_clusterrole.yaml
  packagemanifests/0.10.1/submariner-routeagent_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  packagemanifests/0.10.1/submariner-routeagent_rbac.authorization.k8s.io_v1_role.yaml
  packagemanifests/0.10.1/submariner-routeagent_rbac.authorization.k8s.io_v1_rolebinding.yaml
  packagemanifests/0.10.1/submariner-routeagent_v1_serviceaccount.yaml
  packagemanifests/0.10.1/submariner.io_brokers.yaml
  packagemanifests/0.10.1/submariner.io_submariners.yaml
  packagemanifests/0.10.1/submariner.v0.10.1.clusterserviceversion.yaml
  packagemanifests/submariner.package.yaml
Labels: backport, ready-to-test

#1544 Split out an API module
  .lichen.yaml
  Makefile
  apis/LICENSE
  apis/go.mod
  apis/go.sum
  apis/submariner/v1alpha1/servicediscovery_types.go
  apis/submariner/v1alpha1/submariner_types.go
  apis/submariner/v1alpha1/versions.go
  controllers/submariner/submariner_controller_test.go
  go.mod
  go.sum
  pkg/images/image_parsing_test.go
  pkg/images/images.go
  pkg/subctl/cmd/join.go
Labels: ready-to-test

#1547 Update the operator API module sha
  go.mod
Labels: ready-to-test

#1543 Rename release subctl devel job
  .github/workflows/release_subctl_on_pushwq.yml
Labels: ready-to-test

#1548 Allow installing on older clusters via `--ignore-requirements`
  pkg/subctl/cmd/join.go
Labels: ready-to-test

#1546 Verify that requested CRDs are generated
  Makefile
Labels: ready-to-test

#1529 Update actions/upload-artifact from 1.0.0 to 2.2.4
  .github/workflows/unit.yml
Labels: dependencies, automation, ready-to-test

#1549 Rename diagnose firewall commands
  pkg/subctl/cmd/diagnose/firewall_tunnel.go
  pkg/subctl/cmd/diagnose/firewall_vxlan.go
Labels: ready-to-test

#1550 Update create-issue-from-file GHA 2.3.2 to 3.0.0
  .github/workflows/periodic.yml
Labels: dependencies, automation, ready-to-test

#1551 Ignore apis/vendor dir in YAML linting
  .yamllint.yml
Labels: automation, ready-to-test
