Repository submariner-io/submariner-operator, pull requests merged in 2021-07, with the labels that each got.

#1463 Fix error check in ValidateExistingGlobalNetworks
  pkg/discovery/globalnet/globalnet.go
Labels: ready-to-test

#1464 Fix panic when setting CoreDNSCustomConfig
  controllers/submariner/servicediscovery_resources.go
Labels: ready-to-test

#1466 Update submariner version
  go.mod
  go.sum
Labels: ready-to-test

#1467 Bump to cobra 1.2.0
  go.mod
  go.sum
Labels: ready-to-test

#1465 Bump survey to v2.2.13
  go.mod
  go.sum
Labels: ready-to-test

#1469 Remove redundant type specification
  pkg/discovery/network/calico_test.go
Labels: ready-to-test

#1470 Mount iptables lock file
  controllers/submariner/gateway_resources.go
Labels: ready-to-test

#1477 Remove mount iptables lock file
  controllers/submariner/gateway_resources.go
Labels: ready-to-test

#1480 Support kubecontexts in subctl benchmark
  pkg/subctl/cmd/benchmark.go
Labels: ready-to-test, subctl

#1485 Run Flake Finder every 2h for 0.10-rc0 testing
  .github/workflows/flake_finder.yml
Labels: automation, ready-to-test

#1478 Increase days until stale to 120
  .github/stale.yml
Labels: ready-to-test

#1484 Proper checks for gateways
  pkg/subctl/cmd/diagnose/cni.go
  pkg/subctl/cmd/diagnose/connections.go
  pkg/subctl/cmd/diagnose/firewall_vxlan.go
  pkg/subctl/cmd/diagnose/tunnel.go
  pkg/subctl/cmd/show/connections.go
  pkg/subctl/cmd/show/endpoints.go
  pkg/subctl/cmd/show/gateways.go
  pkg/subctl/cmd/show/networks.go
  pkg/subctl/cmd/show/versions.go
Labels: ready-to-test

#1486 Fix subctl diagnose hostname mismatch issue
  pkg/subctl/cmd/diagnose/firewall.go
  pkg/subctl/cmd/diagnose/firewall_vxlan.go
  pkg/subctl/cmd/diagnose/tunnel.go
Labels: backport, ready-to-test

#1489 Migrate to RBAC v1
  config/rbac/auth_proxy/auth_proxy_client_clusterrole.yaml
Labels: ready-to-test

#1493 Adjust to the updated CreateAnew
  go.mod
  go.sum
  pkg/subctl/operator/brokercr/ensure.go
  pkg/subctl/operator/submarinercr/ensure.go
Labels: ready-to-test

#1494 Remove project-specific gitlint configuration
  .gitlint
Labels: ready-to-test

#1498 Fix panic in subctl show connections
  go.mod
  go.sum
  pkg/subctl/cmd/diagnose/cni.go
  pkg/subctl/cmd/diagnose/connections.go
  pkg/subctl/cmd/diagnose/tunnel.go
  pkg/subctl/cmd/execute.go
  pkg/subctl/cmd/show/connections.go
  pkg/subctl/cmd/show/endpoints.go
  pkg/subctl/cmd/show/gateways.go
Labels: ready-to-test

#1499 Support diagnose tunnel on previous Submariner releases
  pkg/subctl/cmd/diagnose/tunnel.go
Labels: backport, ready-to-test

#1504 Remove test to check log.prev
  scripts/kind-e2e/lib_subctl_gather_test.sh
Labels: ready-to-test

#1492 Do not collect duplicated information
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: ready-to-test

#1473 0.9 backport: Truncate token prefixes for long cluster ids
  pkg/broker/rbac.go
Labels: ready-to-test

#1503 Support microshift deployments, with no dns operator
  controllers/servicediscovery/servicediscovery_controller.go
  controllers/servicediscovery/servicediscovery_controller_test.go
Labels: 0.10.0-testday, ready-to-test

#1500 Update cloud prepare commands to use new deployer
  go.mod
  go.sum
  pkg/subctl/cmd/cloud/aws/aws.go
  pkg/subctl/cmd/cloud/cleanup/aws.go
  pkg/subctl/cmd/cloud/prepare/aws.go
Labels: ready-to-test

#1495 Include globalnet 2.0 resources in subctl gather
  pkg/subctl/cmd/gather.go
  pkg/subctl/cmd/gather/cni.go
  pkg/subctl/cmd/gather/connectivity.go
  pkg/subctl/cmd/gather/logs.go
  scripts/kind-e2e/lib_subctl_gather_test.sh
Labels: globalnet, ready-to-test

#1505 Better handling of gateways in `cloud preapre`
  pkg/subctl/cmd/cloud/prepare/aws.go
Labels: ready-to-test

#1515 Run Flake Finder every 2h for 0.10.0 testing
  .github/workflows/flake_finder.yml
Labels: automation, ready-to-test
