Repository submariner-io/submariner-operator, pull requests merged in 2021-03, with the labels that each got.

#1084 generate-clientset needs go mod vendor
  Makefile
Labels: automation

#1082 Bump to controller-gen 0.4.1
  Dockerfile.dapper
  config/crd/bases/submariner.io_brokers.yaml
  config/crd/bases/submariner.io_servicediscoveries.yaml
  config/crd/bases/submariner.io_submariners.yaml
Labels: dependencies

#1170 Drop the host mounts for GN and RA
  controllers/submariner/submariner_controller.go
  scripts/kind-e2e/lib_operator_verify_subm.sh
Labels: release-note

#1184 Add minimal K8s version matrix to periodic E2E
  .github/workflows/flake_finder.yml
Labels: automation
