Repository submariner-io/submariner-operator, pull requests merged in 2021-02, with the labels that each got.

#1025 Tag released image with branch name
  .github/workflows/release.yml
Labels: backport

#1062 Log status update errors without failing
  controllers/submariner/submariner_controller.go
Labels: backport

#1045 fix(subctl): image-override will override the version and repository properties
  pkg/subctl/cmd/join.go
Labels: backport

#1068 Publish subctl for devel and release-xxx
  .github/workflows/subctl_bleeding_edge.yml
Labels: backport

#1066 Use shared GHAs from Shipyard
  .github/workflows/e2e.yml
  .github/workflows/flake_finder.yml
  .github/workflows/upgrade-e2e.yml
Labels: automation

#1070 Fix subctl cutting edge subctl
  .github/workflows/subctl_cutting_edges.yml
Labels: backport

#1073 Fix README link to latest subctl release
  README.md
Labels: documentation

#1081 Rename connections metric to requested_connections
  controllers/submariner/submariner_metrics.go
Labels: metrics

#1094 fix: parse operator image url enhancement
  pkg/images/images.go
Labels: subctl

#1077 Refactor subctl release GHAs
  .github/workflows/release_subctl.yml
  .github/workflows/release_subctl_devel.yml
Labels: automation
