Repository submariner-io/submariner-operator, pull requests merged in 2021-04, with the labels that each got.

#1183 Test K8s versions 1.18, 1.19, and 1.20 in E2E
  .github/workflows/e2e.yml
Labels: automation

#1230 Drop "verify-connectivity"
  pkg/subctl/cmd/verify_connectivity.go
Labels: UX, subctl

#1233 Pull in optional 0.9 API fixes
  config/crd/bases/submariner.io_submariners.yaml
  go.mod
  go.sum
Labels: upgrade

#1242 Fix show connection IP output
  pkg/subctl/cmd/show_connections.go
Labels: UX

#1243 Add average rtt to subctl show connections
  pkg/subctl/cmd/show_connections.go
Labels: UX

#1244 Folding column printer
  pkg/subctl/cmd/show_connections.go
  pkg/subctl/table/table.go
Labels: UX

#1282 Additional gather details
  pkg/subctl/cmd/gather/cni.go
Labels: 0.9.0-testday

#1248 Add globalnet+all-K8s-versions to flake finder
  .github/workflows/flake_finder.yml
Labels: automation

#1215 Use contexts for subctl verify
  pkg/subctl/cmd/benchmark.go
  pkg/subctl/cmd/verify.go
  scripts/kind-e2e/e2e.sh
Labels: UX

#1308 Disable the DCO GHA
  .github/workflows/linting.yml
Labels: cncf

#1306 fix: image-override should not update the version/repo in submariner cr
  pkg/subctl/cmd/join.go
Labels: bug, subctl

#1272 Capture sysctl -a as part of the route agent logs in gather
  pkg/subctl/cmd/gather/cni.go
Labels: 0.9.0-testday, gatherdata, subctl

#1307 refactor: separate between the component and the image names
  controllers/servicediscovery/servicediscovery_controller.go
  controllers/submariner/netwokplugin_syncer.go
  controllers/submariner/submariner_controller.go
  pkg/images/images.go
  pkg/names/names.go
  pkg/subctl/cmd/join.go
  pkg/subctl/cmd/show_versions.go
  pkg/subctl/operator/submarinerop/deployment/ensure.go
Labels: subctl

#1309 Change validate to diagnose
  pkg/subctl/cmd/validate.go
  pkg/subctl/cmd/validate_all.go
  pkg/subctl/cmd/validate_cni.go
  pkg/subctl/cmd/validate_connections.go
  pkg/subctl/cmd/validate_deployment.go
  pkg/subctl/cmd/validate_firewall.go
  pkg/subctl/cmd/validate_fw_metrics.go
  pkg/subctl/cmd/validate_fw_vxlan.go
  pkg/subctl/cmd/validate_k8sversion.go
  pkg/subctl/cmd/validate_kubeproxy.go
  pkg/subctl/cmd/validate_tunnel.go
Labels: subctl
