Repository submariner-io/submariner-operator, pull requests merged in 2021-06, with the labels that each got.

#1388 ClusterRoles for Globalnet 2.0 CRDs
  config/rbac/submariner-globalnet/cluster_role.yaml
Labels: ready-to-test

#1393 Update ref to Submariner
  go.mod
  go.sum
Labels: ready-to-test

#1396 Allow lighthouse-agent access to globalingressips
  config/rbac/lighthouse-agent/cluster_role.yaml
Labels: ready-to-test

#1392 Use short Kubernetes versions
  .github/workflows/e2e-full.yml
  .github/workflows/flake_finder.yml
Labels: ready-to-test

#1401 Restrict the gateway capabilities
  controllers/submariner/gateway_resources.go
  scripts/kind-e2e/lib_operator_verify_subm.sh
Labels: ready-to-test, security

#1403 Update ref to Submariner
  go.mod
  go.sum
Labels: ready-to-test

#1407 Include delete role for globalIngress object
  config/rbac/submariner-globalnet/cluster_role.yaml
Labels: ready-to-test

#1406 Implement LoadBalancer support in the operator
  apis/submariner/v1alpha1/submariner_types.go
  apis/submariner/v1alpha1/zz_generated.deepcopy.go
  controllers/helpers/helpers.go
  controllers/submariner/gateway_resources.go
  controllers/submariner/loadbalancer_resources.go
  controllers/submariner/submariner_controller.go
  pkg/subctl/cmd/join.go
Labels: P1, enhancement, ready-to-test

#1408 Allow disabling the dedicated gateways created by cloud prepare
  go.mod
  go.sum
  pkg/subctl/cmd/cloud/prepare/aws.go
Labels: P1, S, ready-to-test

#1365 Get network details from Submariner CR
  pkg/discovery/network/network.go
  pkg/subctl/cmd/show_networks.go
Labels: bug, ready-to-test

#1364 Refactor/Rename validate commands
  pkg/internal/cli/status.go
  pkg/subctl/cmd/deploybroker.go
  pkg/subctl/cmd/diagnose/all.go
  pkg/subctl/cmd/diagnose/cni.go
  pkg/subctl/cmd/diagnose/connections.go
  pkg/subctl/cmd/diagnose/deployment.go
  pkg/subctl/cmd/diagnose/diagnose.go
  pkg/subctl/cmd/diagnose/firewall.go
  pkg/subctl/cmd/diagnose/firewall_metrics.go
  pkg/subctl/cmd/diagnose/firewall_vxlan.go
  pkg/subctl/cmd/diagnose/k8s_version.go
  pkg/subctl/cmd/diagnose/kubeproxy.go
  pkg/subctl/cmd/diagnose/tunnel.go
  pkg/subctl/cmd/execute.go
  pkg/subctl/cmd/export.go
  pkg/subctl/cmd/gather.go
  pkg/subctl/cmd/join.go
  pkg/subctl/cmd/resource.go
  pkg/subctl/cmd/root.go
  pkg/subctl/cmd/show.go
  pkg/subctl/cmd/show_all.go
  pkg/subctl/cmd/show_connections.go
  pkg/subctl/cmd/show_endpoints.go
  pkg/subctl/cmd/show_gateways.go
  pkg/subctl/cmd/show_versions.go
  pkg/subctl/cmd/validate_all.go
  pkg/subctl/cmd/validate_connections.go
  pkg/subctl/cmd/validate_deployment.go
  pkg/subctl/cmd/validate_fw_metrics.go
  pkg/subctl/cmd/validate_fw_vxlan.go
  pkg/subctl/cmd/validate_k8sversion.go
  pkg/subctl/cmd/validate_kubeproxy.go
  pkg/subctl/cmd/validate_tunnel.go
  pkg/subctl/cmd/verify.go
  pkg/subctl/cmd/version/version.go
  pkg/subctl/main.go
  pkg/subctl/resource/schedule_pod.go
  scripts/kind-e2e/e2e.sh
Labels: ready-to-test

#1422 Add gateway container ports to match up the LoadBalancer
  controllers/submariner/gateway_resources.go
  controllers/submariner/loadbalancer_resources.go
Labels: ready-to-test

#1424 When a cluster id is invalid, show the error
  pkg/subctl/cmd/join.go
Labels: ready-to-test

#1421 Handle the Broker CRD in Makefile
  Makefile
Labels: ready-to-test

#1425 Subctl diagnose all should run on all clusters
  pkg/subctl/cmd/diagnose/all.go
  pkg/subctl/cmd/execute.go
Labels: ready-to-test

#1431 Mount iptables xtables.lock file in globalnet container
  controllers/submariner/globalnet_resources.go
Labels: backport, ready-to-test

#1433 Avoid printing throughput output twice with verbose
  pkg/subctl/benchmark/throughput.go
Labels: ready-to-test

#1437 Use globalnetv2 enabled submariner and lighthouse
  go.mod
  go.sum
  pkg/subctl/benchmark/latency.go
  pkg/subctl/benchmark/throughput.go
Labels: globalnet, ready-to-test

#1404 Refactor restconfig parts to its own module
  pkg/subctl/cmd/cloud/aws/aws.go
  pkg/subctl/cmd/deploybroker.go
  pkg/subctl/cmd/diagnose/cni.go
  pkg/subctl/cmd/diagnose/tunnel.go
  pkg/subctl/cmd/execute.go
  pkg/subctl/cmd/export.go
  pkg/subctl/cmd/gather.go
  pkg/subctl/cmd/join.go
  pkg/subctl/cmd/resource.go
  pkg/subctl/cmd/root.go
  pkg/subctl/cmd/show.go
  pkg/subctl/cmd/show_all.go
  pkg/subctl/cmd/show_connections.go
  pkg/subctl/cmd/show_endpoints.go
  pkg/subctl/cmd/show_gateways.go
  pkg/subctl/cmd/show_networks.go
  pkg/subctl/cmd/show_versions.go
  pkg/subctl/cmd/utils/restconfig/restconfig.go
  pkg/subctl/cmd/utils/utils.go
  pkg/subctl/cmd/verify.go
Labels: ready-to-test, technical-debt

#1440 Update submariner version
  go.mod
  go.sum
Labels: ready-to-test

#1405 Finish refactoring exit* functions from subctl cmd
  pkg/subctl/cmd/deploybroker.go
  pkg/subctl/cmd/export.go
  pkg/subctl/cmd/gather.go
  pkg/subctl/cmd/join.go
  pkg/subctl/cmd/resource.go
  pkg/subctl/cmd/root.go
  pkg/subctl/cmd/show_all.go
  pkg/subctl/cmd/show_connections.go
  pkg/subctl/cmd/show_endpoints.go
  pkg/subctl/cmd/show_gateways.go
  pkg/subctl/cmd/show_networks.go
  pkg/subctl/cmd/show_versions.go
  pkg/subctl/cmd/verify.go
Labels: ready-to-test, technical-debt

#1438 Error on invalid --image-override name
  pkg/names/names.go
  pkg/subctl/cmd/join.go
Labels: ready-to-test

#1260 Write summary of cluster to HTML file
  go.mod
  pkg/subctl/cmd/gather.go
  pkg/subctl/cmd/gather/cni.go
  pkg/subctl/cmd/gather/layout.gohtml
  pkg/subctl/cmd/gather/logs.go
  pkg/subctl/cmd/gather/resource.go
  pkg/subctl/cmd/gather/summary.go
  pkg/subctl/cmd/gather/types.go
Labels: ready-to-test

#1443 Add deletecollection role for globalIngressIPs
  config/rbac/submariner-globalnet/cluster_role.yaml
Labels: ready-to-test

#1445 Remove Dockerfile.dapper
  .gitignore
  Dockerfile.dapper
Labels: ready-to-test

#1446 Remove ctx arguments from resource.For...
  go.mod
  go.sum
  pkg/utils/createorupdate.go
Labels: ready-to-test

#1444 Add a cross-build check
  .github/workflows/cross.yml
Labels: ready-to-test

#1416 Configure monitoring as a core service on OCP
  config/rbac/kustomization.yaml
  config/rbac/submariner-metrics-reader/role.yaml
  config/rbac/submariner-metrics-reader/role_binding.yaml
  config/rbac/submariner-operator/cluster_role.yaml
  controllers/metrics/metrics.go
  go.mod
  go.sum
  main.go
  pkg/metrics/metrics.go
  pkg/metrics/service-monitor.go
  pkg/subctl/operator/common/embeddedyamls/generators/yamls2go.go
  pkg/subctl/operator/submarinerop/serviceaccount/ensure.go
Labels: ready-to-test, release-note-needed

#1449 Fix submariner-networkplugin-syncer container name
  controllers/submariner/np_syncer_resources.go
Labels: ready-to-test

#1450 Change subctl devel release to use GH CLI
  .github/workflows/release_subctl_devel.yml
Labels: backport, ready-to-test

#1434 Restrict route-agent /run to /run/xtables.lock
  controllers/submariner/route_agent_resources.go
Labels: ready-to-test

#1456 Some fixes for `subctl-devel` release job
  .github/workflows/release_subctl_devel.yml
Labels: ready-to-test

#1447 Remove unnecessary print
  pkg/subctl/cmd/gather/summary.go
Labels: ready-to-test

#1457 Truncate token prefixes for long cluster ids
  pkg/broker/rbac.go
Labels: ready-to-test

#1452 Change globalCIDR to 242.254.x.0
  controllers/submariner/broker_controller.go
  pkg/discovery/globalnet/globalnet.go
  pkg/discovery/globalnet/globalnet_test.go
  pkg/subctl/cmd/deploybroker.go
Labels: globalnet, ready-to-test

#1461 Validate old globalnet only if globalnet enabled
  pkg/subctl/cmd/deploybroker.go
Labels: ready-to-test

#1441 Refactor show to its own pkg
  pkg/subctl/cmd/export.go
  pkg/subctl/cmd/join.go
  pkg/subctl/cmd/root.go
  pkg/subctl/cmd/show/all.go
  pkg/subctl/cmd/show/connections.go
  pkg/subctl/cmd/show/endpoints.go
  pkg/subctl/cmd/show/gateways.go
  pkg/subctl/cmd/show/networks.go
  pkg/subctl/cmd/show/show.go
  pkg/subctl/cmd/show/versions.go
  pkg/subctl/cmd/show_all.go
  pkg/subctl/cmd/show_networks.go
  pkg/subctl/main.go
Labels: ready-to-test

#1462 Add linter to check no "Apply suggestions" commits
  .github/workflows/linting.yml
Labels: automation, ready-to-test
