Repository submariner-io/submariner-operator, pull requests merged in 2021-05, with the labels that each got.

#1352 Add kube flags to cloud commands
  pkg/subctl/cmd/root.go
Labels: backport

#1357 Don't run certain GHA jobs on forks
  .github/workflows/flake_finder.yml
  .github/workflows/periodic.yml
  .github/workflows/release.yml
  .github/workflows/release_subctl.yml
  .github/workflows/release_subctl_devel.yml
Labels: automation

#1363 fix(bundle): add the missing gateway clusterrole/clusterrolebinding
  bundle/manifests/submariner-gateway_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/submariner-gateway_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  config/rbac/kustomization.yaml
  packagemanifests/0.9.0/submariner-gateway_rbac.authorization.k8s.io_v1_clusterrole.yaml
  packagemanifests/0.9.0/submariner-gateway_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
Labels: backport, blocker, bug

#1367 Use go-semver instead of go-version
  go.mod
  pkg/subctl/cmd/root.go
Labels: cncf, dependencies

#1355 Fix broken `--kubecontext`
  pkg/subctl/cmd/deploybroker.go
  pkg/subctl/cmd/export.go
  pkg/subctl/cmd/gather.go
  pkg/subctl/cmd/join.go
  pkg/subctl/cmd/root.go
  pkg/subctl/cmd/show.go
  pkg/subctl/cmd/validate.go
  pkg/subctl/cmd/verify.go
Labels: backport

#1366 Add a license-checking job
  .github/workflows/linting.yml
  .lichen.yaml
  Dockerfile.dapper
  Makefile
  go.mod
  go.sum
Labels: cncf

#1370 Add CII badge, remove PR-triggered badges
  README.md
Labels: cncf, documentation

#1372 Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cncf, documentation, ready-to-test

#1361 Run full E2E matrix only when PR approved
  .github/workflows/e2e-full.yml
  .github/workflows/e2e.yml
Labels: ready-to-test

#1377 Add bot config for labelling when approved
  .submarinerbot.yaml
Labels: ready-to-test

#1379 When comparing CRDs, only compare CRDs
  .github/workflows/linting.yml
Labels: ready-to-test

#1383 Don't run E2E on push
  .github/workflows/release.yml
Labels: ready-to-test

#1374 Fix some supply-chain vulnerabilities
  Dockerfile.dapper
  Makefile
  go.mod
  go.sum
  scripts/operator-sdk-signing-key.asc
  scripts/operator-sdk-signing-keyring.gpg
  scripts/operator-sdk.sha256
  tools.go
Labels: ready-to-test

#1386 Add a branch check job
  .github/workflows/branch.yml
Labels: ready-to-test

#1390 Fan out submariner controller functions
  controllers/submariner/daemonsets.go
  controllers/submariner/gateway_resources.go
  controllers/submariner/globalnet_resources.go
  controllers/submariner/np_syncer_resources.go
  controllers/submariner/route_agent_resources.go
  controllers/submariner/servicediscovery_resources.go
  controllers/submariner/submariner_controller.go
Labels: ready-to-test

#1391 Pass down POD_NAME to submariner-gateway
  controllers/submariner/gateway_resources.go
Labels: ready-to-test

#1354 Allow getting infra ID and region from OCP metadata
  pkg/subctl/cmd/cloud/aws/aws.go
Labels: backport, ready-to-test
