Repository submariner-io/submariner-operator, pull requests merged in 2022-07, with the labels that each got.

#2128 [Backport] Fix intermittent failure with diagnose metrics cmd
  pkg/subctl/cmd/diagnose/firewall_metrics.go
Labels: ready-to-test

#2129 Add K8s 1.24 E2E, EoL K8s 1.21, fix docs
  .github/workflows/e2e-all-k8s.yml
  .github/workflows/e2e-full.yml
  .github/workflows/flake_finder.yml
Labels: ready-to-test, e2e-all-k8s, maintenance

#2134 Bump x/text to address CVE-2021-38561
  go.mod
  go.sum
Labels: backport, ready-to-test

#2138 Add submariner-gateway role permissions for leases
  bundle/manifests/submariner-gateway_rbac.authorization.k8s.io_v1_role.yaml
  config/rbac/submariner-gateway/role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#2153 Run the upgrade job on devel only
  .github/workflows/upgrade-e2e.yml
Labels: backport, ready-to-test, maintenance

#2149 Automated backport of #2134: Bump x/text to address CVE-2021-38561
  go.mod
  go.sum
Labels: ready-to-test, automated-backport

#2148 Automated backport of #2134: Bump x/text to address CVE-2021-38561
  go.mod
  go.sum
Labels: ready-to-test, automated-backport

#2143 Fix subctl verify test with lighthouse enabled
  scripts/test/e2e.sh
Labels: ready-to-test

#2155 Automated backport of #2153: Run the upgrade job on devel only
  .github/workflows/upgrade-e2e.yml
Labels: ready-to-test, automated-backport

#2147 Fix KIND deployments using ovn
  Makefile
Labels: ready-to-test

#2154 Automated backport of #2153: Run the upgrade job on devel only
  .github/workflows/upgrade-e2e.yml
Labels: ready-to-test, automated-backport

#2150 Add a GHA to test subctl
  .github/workflows/subctl-unit.yml
Labels: ready-to-test

#2146 Support for default subnet in weavenet CNI discovery
  pkg/discovery/network/weavenet.go
Labels: ready-to-test

#2126 Remove uses of the Submariner clientset
  .licenserc.json
  Makefile
  controllers/controllers.go
  controllers/submariner/submariner_controller.go
  controllers/submariner/submariner_networkdiscovery.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/submariner/v1alpha1/broker.go
  pkg/client/clientset/versioned/typed/submariner/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/submariner/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/submariner/v1alpha1/fake/fake_broker.go
  pkg/client/clientset/versioned/typed/submariner/v1alpha1/fake/fake_servicediscovery.go
  pkg/client/clientset/versioned/typed/submariner/v1alpha1/fake/fake_submariner.go
  pkg/client/clientset/versioned/typed/submariner/v1alpha1/fake/fake_submariner_client.go
  pkg/client/clientset/versioned/typed/submariner/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/submariner/v1alpha1/servicediscovery.go
  pkg/client/clientset/versioned/typed/submariner/v1alpha1/submariner.go
  pkg/client/clientset/versioned/typed/submariner/v1alpha1/submariner_client.go
  pkg/client/default_producer.go
  pkg/client/producer.go
  pkg/client/restconfig_producer.go
  pkg/discovery/network/network.go
  test/e2e/cleanup/submariner.go
Labels: ready-to-test
