Repository submariner-io/submariner-operator, pull requests merged in 2022-04, with the labels that each got.

#1993 Use multi-active-gw dependencies
  .github/workflows/branch.yml
  .github/workflows/e2e-all-k8s.yml
  .github/workflows/e2e-full.yml
  .github/workflows/e2e.yml
  .github/workflows/flake_finder.yml
  .github/workflows/release.yml
  .github/workflows/release_subctl_on_push.yml
  .github/workflows/subctl.yml
  .github/workflows/upgrade-e2e.yml
  Makefile
  controllers/submariner/submariner_controller_test.go
  internal/pods/schedule.go
  pkg/images/images.go
  pkg/version/version.go
Labels: ready-to-test

#1991 Remove duplicate output for subctl show versions
  pkg/subctl/cmd/show/versions.go
Labels: ready-to-test

#1995 Remove references to lighthouse.submariner.io CRDs
  bundle/manifests/submariner-gateway_rbac.authorization.k8s.io_v1_role.yaml
  bundle/manifests/submariner-globalnet_rbac.authorization.k8s.io_v1_role.yaml
  bundle/manifests/submariner-lighthouse-coredns_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/submariner-routeagent_rbac.authorization.k8s.io_v1_role.yaml
  config/rbac/lighthouse-coredns/cluster_role.yaml
  config/rbac/submariner-gateway/role.yaml
  config/rbac/submariner-globalnet/role.yaml
  config/rbac/submariner-route-agent/role.yaml
  pkg/embeddedyamls/yamls.go
  pkg/lighthouse/crds.go
Labels: ready-to-test, maintenance

#1997 Use Dependabot to update GHAs, now supports SHAs
  .github/dependabot.yml
Labels: ready-to-test, maintenance

#1973 Change RHOS default image type in subctl
  pkg/subctl/cmd/cloud/prepare/rhos.go
Labels: backport, backport-handled, ready-to-test

#1996 Automated backport of #1973: Change default image type
  pkg/subctl/cmd/cloud/prepare/rhos.go
Labels: ready-to-test, automated-backport

#1998 Remove unnecessary parentheses
  controllers/submariner/daemonsets.go
  internal/env/term.go
  pkg/deploy/submariner.go
  pkg/discovery/globalnet/globalnet.go
  pkg/images/images.go
  pkg/subctl/cmd/join.go
  pkg/uninstall/all.go
  pkg/version/version.go
Labels: ready-to-test

#2002 Print message when no kube config provided
  cmd/subctl/execute/execute.go
  pkg/subctl/cmd/execute.go
Labels: backport, ready-to-test

#2005 Use unique name for all-K8s E2E job
  .github/workflows/e2e-all-k8s.yml
Labels: ready-to-test, maintenance

#1980 Move uninstall command to new subctl implementation
  cmd/subctl/uninstall.go
Labels: ready-to-test

#2010 Add execute wrapper func that checks Submariner installed
  cmd/subctl/execute/execute.go
  internal/constants/constants.go
Labels: ready-to-test

#2011 Wrap parameter/return lists as expected by gofumpt
  controllers/helpers/helpers.go
  controllers/metrics/metrics.go
  controllers/servicediscovery/cleanup.go
  controllers/servicediscovery/servicediscovery_controller.go
  controllers/submariner/daemonsets.go
  controllers/submariner/gateway_resources.go
  controllers/submariner/globalnet_resources.go
  controllers/submariner/loadbalancer_resources.go
  controllers/submariner/np_syncer_resources.go
  controllers/submariner/route_agent_resources.go
  controllers/submariner/servicediscovery_resources.go
  controllers/uninstall/uninstall.go
  go.mod
  internal/pods/schedule.go
  pkg/broker/ensure.go
  pkg/broker/file.go
  pkg/broker/globalcidr_cm.go
  pkg/crd/updater.go
  pkg/deploy/operator.go
  pkg/deploy/servicediscovery.go
  pkg/deploy/submariner.go
  pkg/discovery/globalnet/globalnet.go
  pkg/discovery/network/network.go
  pkg/join/join.go
  pkg/metrics/metrics.go
  pkg/subctl/cmd/cloud/aws/aws.go
  pkg/subctl/cmd/cloud/gcp/gcp.go
  pkg/subctl/cmd/cloud/generic/generic.go
  pkg/subctl/cmd/cloud/rhos/rhos.go
  pkg/subctl/cmd/diagnose/firewall.go
  pkg/subctl/cmd/join.go
  pkg/subctl/operator/lighthouse/ensure.go
  tools.go
Labels: ready-to-test

#1806 Make `ForCluster` return cluster config and name
  cmd/subctl/deploybroker.go
  cmd/subctl/export.go
  cmd/subctl/join.go
  cmd/subctl/uninstall.go
  internal/restconfig/restconfig.go
  pkg/subctl/cmd/cloud/aws/aws.go
  pkg/subctl/cmd/cloud/gcp/gcp.go
  pkg/subctl/cmd/cloud/generic/generic.go
  pkg/subctl/cmd/cloud/rhos/rhos.go
  pkg/subctl/cmd/deploybroker.go
  pkg/subctl/cmd/diagnose/firewall_tunnel.go
  pkg/subctl/cmd/uninstall.go
Labels: ready-to-test, next-version-candidate

#2012 Rearrange constants alphabetically
  internal/constants/constants.go
Labels: ready-to-test

#2015 Add new subctl diagnose command
  .github/workflows/e2e-new-subctl.yml
  cmd/subctl/diagnose.go
  pkg/cluster/info.go
Labels: ready-to-test
