Repository submariner-io/submariner-operator, pull requests merged in 2022-03, with the labels that each got.

#1861 Add globalnet diagnose to subctl
  pkg/subctl/cmd/diagnose/all.go
  pkg/subctl/cmd/diagnose/globalnet.go
Labels: ready-to-test

#1884 Fix diagnose inter-cluster with vxlan cable driver
  pkg/subctl/cmd/diagnose/firewall_tunnel.go
Labels: ready-to-test

#1882 Warn user when generic plugin is detected in diagnose
  pkg/subctl/cmd/diagnose/cni.go
Labels: UX, ready-to-test, release-note-needed

#1899 Fix extraneous uninstall pods present after cleanup complete
  controllers/servicediscovery/cleanup.go
  controllers/servicediscovery/servicediscovery_controller_test.go
  controllers/submariner/cleanup.go
  controllers/submariner/submariner_controller_test.go
  go.mod
  go.sum
Labels: backport, ready-to-test

#1912 Fix extraneous uninstall pods present after cleanup complete
  controllers/servicediscovery/cleanup.go
  controllers/servicediscovery/servicediscovery_controller_test.go
  controllers/submariner/cleanup.go
  controllers/submariner/submariner_controller_test.go
  go.mod
  go.sum
Labels: ready-to-test

#1908 Add cluster name to `subctl uninstall`
  pkg/subctl/cmd/uninstall.go
  pkg/uninstall/all.go
Labels: backport, ready-to-test

#1909 Fix subctl show networks,versions output
  pkg/subctl/cmd/show/networks.go
  pkg/subctl/cmd/show/versions.go
Labels: backport, ready-to-test

#1916 Print out brokers information on `subctl show all`
  pkg/subctl/cmd/show/all.go
  pkg/subctl/cmd/show/brokers.go
  pkg/subctl/cmd/show/versions.go
Labels: backport, ready-to-test

#1910 Capture API warnings on `subctl gather`
  pkg/subctl/cmd/gather/gather.go
Labels: backport, ready-to-test

#1907 Change uninstall to be reentrant
  pkg/uninstall/all.go
Labels: backport, ready-to-test

#1918 Fix subctl show networks and versions output
  pkg/subctl/cmd/show/networks.go
  pkg/subctl/cmd/show/versions.go
Labels: ready-to-test

#1905 Always end gather status
  pkg/subctl/cmd/gather/gather.go
Labels: backport, ready-to-test

#1922 Backport 0.12: Add cluster name to `subctl uninstall`
  pkg/subctl/cmd/uninstall.go
  pkg/uninstall/all.go
Labels: ready-to-test

#1923 Backport 0.12: Capture API warnings on `subctl gather`
  pkg/subctl/cmd/gather/gather.go
Labels: ready-to-test

#1924 Backport 0.12: Print out brokers information on `subctl show all`
  pkg/subctl/cmd/show/all.go
  pkg/subctl/cmd/show/brokers.go
  pkg/subctl/cmd/show/versions.go
Labels: ready-to-test

#1917 Set default value of dedicated-gw to true for GCP and RHOS
  pkg/subctl/cmd/cloud/prepare/gcp.go
  pkg/subctl/cmd/cloud/prepare/rhos.go
Labels: backport, ready-to-test

#1925 Backport 0.12: always end gather status
  pkg/subctl/cmd/gather/gather.go
Labels: ready-to-test

#1920 Reduce verbosity of controller reconciliation
  controllers/servicediscovery/servicediscovery_controller.go
  controllers/submariner/cleanup.go
  controllers/submariner/submariner_controller.go
  controllers/submariner/submariner_networkdiscovery.go
Labels: backport, ready-to-test

#1929 Backport 0.12: Reduce verbosity of controller reconciliation
  controllers/servicediscovery/servicediscovery_controller.go
  controllers/submariner/cleanup.go
  controllers/submariner/submariner_controller.go
  controllers/submariner/submariner_networkdiscovery.go
Labels: ready-to-test

#1892 Add packagedoc-lint PR linting, fix errors
  .github/workflows/linting.yml
  api/submariner/v1alpha1/register.go
  api/submariner/v1alpha1/versions.go
  cmd/main.go
  cmd/subctl/deploybroker.go
  controllers/metrics/metrics.go
  controllers/servicediscovery/servicediscovery_controller.go
  controllers/servicediscovery/servicediscovery_controller_test.go
  controllers/submariner/submariner_networkdiscovery.go
  internal/exit/exit.go
  internal/image/image.go
  pkg/broker/globalcidr_cm.go
  pkg/discovery/network/calico.go
  pkg/discovery/network/calico_test.go
  pkg/embeddedyamls/generate.go
  pkg/images/image_parsing_test.go
  pkg/images/images.go
  pkg/lighthouse/crds.go
  pkg/names/names.go
  pkg/scc/update.go
  pkg/subctl/benchmark/latency.go
  pkg/subctl/benchmark/throughput.go
  pkg/subctl/cmd/benchmark.go
  pkg/subctl/cmd/diagnose/all.go
  pkg/subctl/cmd/diagnose/cni.go
  pkg/subctl/cmd/diagnose/connections.go
  pkg/subctl/cmd/diagnose/deployment.go
  pkg/subctl/cmd/diagnose/diagnose.go
  pkg/subctl/cmd/diagnose/firewall_metrics.go
  pkg/subctl/cmd/diagnose/firewall_tunnel.go
  pkg/subctl/cmd/diagnose/firewall_vxlan.go
  pkg/subctl/cmd/diagnose/globalnet.go
  pkg/subctl/cmd/diagnose/k8s_version.go
  pkg/subctl/cmd/diagnose/kubeproxy.go
  pkg/subctl/cmd/execute.go
  pkg/subctl/cmd/gather/logs.go
  pkg/subctl/cmd/gather/operator.go
  pkg/subctl/cmd/gather/resource.go
  pkg/subctl/cmd/gather/types.go
  pkg/subctl/cmd/resource.go
  pkg/subctl/cmd/show/all.go
  pkg/subctl/cmd/show/connections.go
  pkg/subctl/cmd/show/endpoints.go
  pkg/subctl/cmd/show/gateways.go
  pkg/subctl/cmd/show/versions.go
  pkg/subctl/datafile/backup.go
  pkg/version/version.go
Labels: automation, backport, ready-to-test

#1933 Add packagedoc-lint linting, fix errors
  .github/workflows/linting.yml
  api/submariner/v1alpha1/register.go
  api/submariner/v1alpha1/versions.go
  cmd/main.go
  cmd/subctl/deploybroker.go
  controllers/metrics/metrics.go
  controllers/servicediscovery/servicediscovery_controller.go
  controllers/servicediscovery/servicediscovery_controller_test.go
  controllers/submariner/submariner_networkdiscovery.go
  internal/exit/exit.go
  internal/image/image.go
  pkg/broker/globalcidr_cm.go
  pkg/discovery/network/calico.go
  pkg/discovery/network/calico_test.go
  pkg/embeddedyamls/generate.go
  pkg/images/image_parsing_test.go
  pkg/images/images.go
  pkg/lighthouse/crds.go
  pkg/names/names.go
  pkg/scc/update.go
  pkg/subctl/benchmark/latency.go
  pkg/subctl/benchmark/throughput.go
  pkg/subctl/cmd/benchmark.go
  pkg/subctl/cmd/diagnose/all.go
  pkg/subctl/cmd/diagnose/cni.go
  pkg/subctl/cmd/diagnose/connections.go
  pkg/subctl/cmd/diagnose/deployment.go
  pkg/subctl/cmd/diagnose/diagnose.go
  pkg/subctl/cmd/diagnose/firewall_metrics.go
  pkg/subctl/cmd/diagnose/firewall_tunnel.go
  pkg/subctl/cmd/diagnose/firewall_vxlan.go
  pkg/subctl/cmd/diagnose/globalnet.go
  pkg/subctl/cmd/diagnose/k8s_version.go
  pkg/subctl/cmd/diagnose/kubeproxy.go
  pkg/subctl/cmd/execute.go
  pkg/subctl/cmd/gather/logs.go
  pkg/subctl/cmd/gather/operator.go
  pkg/subctl/cmd/gather/resource.go
  pkg/subctl/cmd/gather/types.go
  pkg/subctl/cmd/resource.go
  pkg/subctl/cmd/show/all.go
  pkg/subctl/cmd/show/connections.go
  pkg/subctl/cmd/show/endpoints.go
  pkg/subctl/cmd/show/gateways.go
  pkg/subctl/cmd/show/versions.go
  pkg/subctl/datafile/backup.go
  pkg/version/version.go
Labels: automation, ready-to-test

#1932 Drop periodic bundle tests
  .github/workflows/periodic.yml
Labels: automation, ready-to-test

#1942 Remove K8s 1.20 tests as it's EOL
  .github/workflows/e2e-all-k8s.yml
  .github/workflows/e2e-full.yml
  .github/workflows/flake_finder.yml
Labels: automation, ready-to-test

#1950 Fix packagedoc-lint error
  pkg/subctl/cmd/show/brokers.go
Labels: bug, documentation, ready-to-test

#1954 Fix golangci-lint v1.44.2 errors
  pkg/subctl/cmd/diagnose/cni.go
  pkg/subctl/cmd/diagnose/firewall.go
Labels: ready-to-test

#1955 Update actions/upload-artifact from 2.2.4 to 3.0.0
  .github/workflows/unit.yml
Labels: automation, ready-to-test

#1958 Use the Kubernetes RFC-1123 validation
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
Labels: backport, ready-to-test

#1963 Backport: Use the Kubernetes RFC-1123 validation
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
Labels: ready-to-test

#1953 Update CODEOWNERS for the multi-active-gw branch
  .github/workflows/branch.yml
  CODEOWNERS
  CODEOWNERS.in
Labels: ready-to-test

#1962 Drop deprecated --colorcodes option
  cmd/subctl/join.go
  pkg/subctl/cmd/join.go
Labels: ready-to-test

#1961 Add JUnit report generation to "subctl verify"
  cmd/subctl/benchmark.go
  cmd/subctl/verify.go
  go.mod
  go.sum
  pkg/subctl/cmd/verify.go
Labels: ready-to-test

#1965 Revert "Backport: Use the Kubernetes RFC-1123 validation"
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
Labels: ready-to-test

#1951 Add support for `subctl join ... --multi-active-gateway=true`
  .github/workflows/unit.yml
  .gitignore
  api/submariner/v1alpha1/submariner_types.go
  cmd/subctl/benchmark.go
  cmd/subctl/join.go
  cmd/subctl/verify.go
  controllers/submariner/gateway_resources.go
  controllers/submariner/globalnet_resources.go
  go.mod
  go.sum
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  pkg/deploy/submariner.go
  pkg/embeddedyamls/yamls.go
  pkg/join/join.go
  pkg/join/options.go
  pkg/subctl/cmd/diagnose/cni.go
  pkg/subctl/cmd/diagnose/firewall.go
  pkg/subctl/cmd/join.go
  pkg/subctl/cmd/verify.go
Labels: ready-to-test

#1986 Backport: Use the Kubernetes RFC-1123 validation
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
Labels: ready-to-test

#1989 Drop IKE port configuration
  cmd/subctl/join.go
  controllers/submariner/gateway_resources.go
  controllers/submariner/submariner_suite_test.go
  pkg/deploy/submariner.go
  pkg/join/join.go
  pkg/join/options.go
  pkg/subctl/cmd/join.go
  scripts/kind-e2e/lib_operator_verify_subm.sh
Labels: ready-to-test, release-note-needed
