Repository submariner-io/submariner-operator, pull requests merged in 2022-02, with the labels that each got.

#1814 Add standard reporter.Interface implementations
  pkg/reporter/klog.go
  pkg/reporter/reporter.go
  pkg/reporter/silent.go
  pkg/reporter/stdout.go
Labels: ready-to-test

#1799 Move pkg/subctl/resource to internal/
  internal/pods/exec.go
  internal/pods/schedule.go
  pkg/subctl/cmd/diagnose/firewall.go
  pkg/subctl/cmd/diagnose/firewall_metrics.go
  pkg/subctl/cmd/diagnose/firewall_tunnel.go
  pkg/subctl/cmd/diagnose/firewall_vxlan.go
  pkg/subctl/cmd/diagnose/kubeproxy.go
  pkg/subctl/cmd/gather/cni.go
  pkg/subctl/resource/util.go
Labels: ready-to-test

#1804 Refactor pkg/subctl/cmd/execute.go
  cmd/subctl/execute/execute.go
  pkg/cluster/info.go
Labels: ready-to-test

#1801 Use reporter interface & clientproducer for gather
  pkg/subctl/cmd/gather/cni.go
  pkg/subctl/cmd/gather/gather.go
  pkg/subctl/cmd/gather/logs.go
  pkg/subctl/cmd/gather/resource.go
  pkg/subctl/cmd/gather/servicediscovery.go
  pkg/subctl/cmd/gather/summary.go
  pkg/subctl/cmd/gather/types.go
Labels: ready-to-test

#1817 Copy export to its own package
  cmd/subctl/export.go
  pkg/service/export.go
Labels: ready-to-test

#1815 Ship our embedded YAMLs and check they're up-to-date
  .github/workflows/linting.yml
  pkg/embeddedyamls/.gitignore
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#1828 Defer calls to status.End()
  cmd/subctl/join.go
  pkg/broker/file.go
  pkg/deploy/broker.go
  pkg/discovery/globalnet/globalnet.go
  pkg/join/join.go
  pkg/reporter/reporter.go
Labels: ready-to-test

#1834 Fix error message when GN is deployed
  pkg/discovery/globalnet/globalnet.go
Labels: globalnet, ready-to-test

#1837 Add globalnet image to list of images copied to local registry
  Makefile
Labels: ready-to-test

#1847 Automated backport of #1702: feat(bundle): support related-images
  Makefile
  config/manager/kustomization.yaml
  config/manager/patches/related-images.deployment.config.yaml
  pkg/images/images.go
Labels: ready-to-test, automated-backport

#1789 Add RHOS support
  go.mod
  go.sum
  pkg/subctl/cmd/cloud/cleanup/cleanup.go
  pkg/subctl/cmd/cloud/cleanup/rhos.go
  pkg/subctl/cmd/cloud/prepare/prepare.go
  pkg/subctl/cmd/cloud/prepare/rhos.go
  pkg/subctl/cmd/cloud/rhos/rhos.go
Labels: ready-to-test

#1845 Allow submariner-globalnet role to create endpoints
  config/rbac/submariner-globalnet/cluster_role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#1802 Netwok-discovery: handle networkType==Calico in OCP
  pkg/discovery/network/openshift4.go
Labels: ready-to-test

#1848 Ensure uninstall components aren't recreated
  controllers/submariner/submariner_controller_test.go
  controllers/uninstall/uninstall.go
Labels: ready-to-test

#1854 Fix GN Pod service account during uninstall
  controllers/submariner/globalnet_resources.go
Labels: ready-to-test

#1856 Fix service account name in network plugin syncer
  controllers/submariner/np_syncer_resources.go
Labels: ready-to-test

#1858 Use constants for Globalnet defaults
  cmd/subctl/deploybroker.go
  pkg/broker/globalcidr_cm.go
Labels: ready-to-test

#1857 Fix return value of uninstall.IsSupportedForVersion
  controllers/servicediscovery/cleanup.go
  controllers/submariner/cleanup.go
  controllers/submariner/submariner_controller_test.go
  controllers/uninstall/uninstall.go
Labels: ready-to-test

#1859 Move resource declarations to point-of-use
  controllers/submariner/gateway_resources.go
  controllers/submariner/globalnet_resources.go
  controllers/submariner/np_syncer_resources.go
  controllers/submariner/route_agent_resources.go
Labels: ready-to-test

#1862 Include delete clusterrole for globalnet sa
  config/rbac/submariner-globalnet/cluster_role.yaml
Labels: ready-to-test

#1864 Update embeddedyamls/yamls.go
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#1860 Add security context to subm-operator deployment
  pkg/subctl/operator/submarinerop/deployment/ensure.go
Labels: ready-to-test

#1868 Remove special handling for api
  Makefile
Labels: ready-to-test

#1871 Don't go:generate unused embedded yamls
  pkg/embeddedyamls/generators/yamls2go.go
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#1874 Add support for `make reload-images`
  Makefile
Labels: ready-to-test

#1875 Delete ServiceDiscovery on Submariner cleanup
  controllers/servicediscovery/cleanup.go
  controllers/submariner/cleanup.go
  controllers/submariner/submariner_controller_test.go
  controllers/uninstall/uninstall.go
  test/e2e/cleanup/service_discovery.go
  test/e2e/cleanup/submariner.go
Labels: ready-to-test

#1838 Rhos dedicated gw
  go.mod
  go.sum
  pkg/subctl/cmd/cloud/cleanup/rhos.go
  pkg/subctl/cmd/cloud/prepare/prepare.go
  pkg/subctl/cmd/cloud/prepare/rhos.go
  pkg/subctl/cmd/cloud/rhos/rhos.go
Labels: ready-to-test, release-note-needed

#1878 Added internal service to gather collection
  pkg/subctl/cmd/gather/gather.go
  pkg/subctl/cmd/gather/servicediscovery.go
Labels: ready-to-test

#1873 Added command to unexport services
  pkg/subctl/cmd/export.go
  pkg/subctl/cmd/root.go
  pkg/subctl/cmd/unexport.go
Labels: ready-to-test

#1879 Fix new linter errors from golangci-lint 1.44.2
  controllers/submariner/daemonsets.go
  controllers/submariner/np_syncer_resources.go
  pkg/client/producer.go
  pkg/crd/updater.go
Labels: automation, ready-to-test

#1877 Add subctl uninstall command
  Makefile
  pkg/subctl/cmd/uninstall.go
  pkg/subctl/operator/servicediscoverycr/ensure.go
  pkg/subctl/operator/submarinercr/ensure.go
  pkg/uninstall/all.go
Labels: ready-to-test
