Repository submariner-io/submariner-operator, pull requests merged in 2022-10, with the labels that each got.

#2264 Additional role privileges for submariner-diagnose
  config/rbac/submariner-diagnose/role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#2272 AIR_GAPPED support in operator
  api/v1alpha1/submariner_types.go
  config/crd/bases/submariner.io_submariners.yaml
  controllers/submariner/gateway_resources.go
  controllers/submariner/submariner_controller.go
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#2278 Automated backport of #2246: Use the default kind CNI
  .shipyard.e2e.yml
Labels: ready-to-test, automated-backport

#2279 Automated backport of #2246: Use the default kind CNI
  .shipyard.e2e.yml
Labels: ready-to-test, automated-backport

#2263 Add Sonar unit test coverage reporting
  .github/workflows/report.yml
  sonar-project.properties
Labels: automation, ready-to-test

#2281 Status AirGappedDeployment field should not be required
  api/v1alpha1/submariner_types.go
  config/crd/bases/submariner.io_submariners.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#2283 Add cluster role privileges for submariner-diagnose
  config/rbac/submariner-diagnose/cluster_role.yaml
  config/rbac/submariner-diagnose/role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#2287 Sonar shallow clone, remove debug
  .github/workflows/report.yml
Labels: automation, ready-to-test

#2282 Add Sonar config to ignore api dir
  sonar-project.properties
Labels: automation, ready-to-test

#2289 Remove space between // and nolint
  controllers/apply/apply.go
  controllers/metrics/metrics.go
  controllers/resource/client.go
  controllers/servicediscovery/cleanup.go
  controllers/servicediscovery/servicediscovery_controller.go
  controllers/submariner/broker_controller.go
  controllers/submariner/cleanup.go
  controllers/submariner/gateway_resources.go
  controllers/submariner/globalnet_resources.go
  controllers/submariner/loadbalancer_resources.go
  controllers/submariner/metrics_proxy_resources.go
  controllers/submariner/np_syncer_resources.go
  controllers/submariner/route_agent_resources.go
  controllers/submariner/servicediscovery_resources.go
  controllers/submariner/submariner_controller.go
  main.go
  pkg/crd/updater.go
  pkg/discovery/globalnet/config_map.go
  pkg/discovery/globalnet/globalnet.go
  pkg/discovery/network/calico.go
  pkg/discovery/network/canal.go
  pkg/discovery/network/generic.go
  pkg/discovery/network/network.go
  pkg/discovery/network/openshift4.go
  pkg/discovery/network/pods.go
  pkg/metrics/service-monitor.go
Labels: ready-to-test

#1850 Add discovery to properly identify flannel cni
  pkg/discovery/network/flannel.go
  pkg/discovery/network/flannel_test.go
  pkg/discovery/network/network.go
  release-notes/20220216-flannel-cni.md
Labels: dependencies, ready-to-test, release-note-needed, confirmed, blocked-on-rereview, release-note-handled

#2288 Add GlobalIngressIPs cluster role privs for submariner-diagnose
  config/rbac/submariner-diagnose/cluster_role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#2292 Add issues:write permission to broken links GHA
  .github/workflows/periodic.yml
Labels: automation, ready-to-test

#2293 Expose `Nettest{Component,Image}`
  pkg/names/names.go
Labels: backport, ready-to-test

#2303 Automated backport of #2293: Expose `Nettest{Component,Image}`
  pkg/names/names.go
Labels: ready-to-test, automated-backport

#2314 Rename DaemonSetStatus and LoadBalancerStatus
  api/v1alpha1/submariner_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/submariner/daemonsets.go
Labels: backport, ready-to-test

#2315 Use the nettest image for the pause container
  controllers/servicediscovery/cleanup.go
  controllers/submariner/cleanup.go
  controllers/uninstall/uninstall.go
Labels: backport, ready-to-test

#2316 Automated backport of #2314: Rename DaemonSetStatus and LoadBalancerStatus
  api/v1alpha1/submariner_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/submariner/daemonsets.go
Labels: automated-backport
