Repository submariner-io/submariner-operator, pull requests merged in 2022-12, with the labels that each got.

#2381 Bump to Go 1.19
  go.mod
  go.sum
Labels: ready-to-test, maintenance

#2375 Run dependabot for go weekly, all updates at once
  .github/dependabot.yml
Labels: automation, ready-to-test

#2382 Use the controller runtime client
  go.mod
  go.sum
  main.go
Labels: backport, ready-to-test

#2387 Automated backport of #2382: Use the controller runtime client
  go.mod
  go.sum
  main.go
Labels: ready-to-test, automated-backport

#2388 Automated backport of #2382: Use the controller runtime client
  controllers/controllers.go
  go.mod
  go.sum
Labels: ready-to-test, automated-backport

#2389 Automated backport of #2382: Use the controller runtime client
  controllers/controllers.go
  go.mod
  go.sum
Labels: ready-to-test, automated-backport

#2393 Use Go 1.19 for the subctl check
  .github/workflows/subctl-unit.yml
Labels: ready-to-test, maintenance

#2407 Bump to Kubernetes 0.26 dependencies
  go.mod
  go.sum
Labels: ready-to-test

#2411 Log information about images loaded
  pkg/images/images.go
Labels: backport, ready-to-test

#2423 Automated backport of #2411: Log information about images loaded
  pkg/images/images.go
Labels: ready-to-test, automated-backport

#2430 Update Submariner to 0.13.3 in go mod
  go.mod
  go.sum
Labels: ready-to-test

#2424 Move the version variable into the main package
  Makefile
  main.go
  pkg/version/version.go
Labels: ready-to-test, maintenance

#2432 Add BrokerCrName constant
  pkg/names/names.go
Labels: ready-to-test
