Repository submariner-io/submariner-operator, pull requests merged in 2022-09, with the labels that each got.

#2222 Fix system tests after latest Shipyard changes
  Makefile
  scripts/test/system.sh
Labels: ready-to-test

#2225 Restore route agent node update privilege
  config/rbac/submariner-route-agent/cluster_role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#2169 diagnose clusterrole: remove pods sections:
  config/rbac/submariner-diagnose/cluster_role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#2230 Add health and readyness probes
  main.go
Labels: check-prometheus, ready-to-test

#2238 Fix shellcheck errors and add to linting GHA
  .github/workflows/linting.yml
  scripts/kustomize/install_kustomize.sh
  scripts/test/e2e.sh
  scripts/test/system.sh
Labels: ready-to-test, maintenance

#2231 Bump Prometheus operator to 0.59.0
  go.mod
  go.sum
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#2236 Don't specify images to preload
  Makefile
Labels: ready-to-test, maintenance

#2235 Add judgment before split the string
  pkg/images/images.go
Labels: ready-to-test

#2237 Add separate RBAC files for OCP
  config/rbac/kustomization.yaml
  config/rbac/lighthouse-agent/ocp_cluster_role.yaml
  config/rbac/lighthouse-agent/ocp_cluster_role_binding.yaml
  config/rbac/lighthouse-coredns/ocp_cluster_role.yaml
  config/rbac/lighthouse-coredns/ocp_cluster_role_binding.yaml
  config/rbac/networkplugin_syncer/ocp_cluster_role.yaml
  config/rbac/networkplugin_syncer/ocp_cluster_role_binding.yaml
  config/rbac/submariner-diagnose/ocp_cluster_role.yaml
  config/rbac/submariner-diagnose/ocp_cluster_role_binding.yaml
  config/rbac/submariner-gateway/ocp_cluster_role.yaml
  config/rbac/submariner-gateway/ocp_cluster_role_binding.yaml
  config/rbac/submariner-globalnet/ocp_cluster_role.yaml
  config/rbac/submariner-globalnet/ocp_cluster_role_binding.yaml
  config/rbac/submariner-operator/ocp_cluster_role.yaml
  config/rbac/submariner-operator/ocp_cluster_role_binding.yaml
  config/rbac/submariner-route-agent/ocp_cluster_role.yaml
  config/rbac/submariner-route-agent/ocp_cluster_role_binding.yaml
  pkg/embeddedyamls/generators/yamls2go.go
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#2234 [0.12-branch] Validate if SM version supports OVNK as part of diagnose
  pkg/subctl/cmd/diagnose/cni.go
Labels: ready-to-test

#2247 Add K8s 1.25 to E2E CI
  .github/workflows/e2e-all-k8s.yml
  .github/workflows/e2e-full.yml
  .github/workflows/flake_finder.yml
Labels: ready-to-test, maintenance

#2246 Use the default kind CNI
  .shipyard.e2e.yml
  .shipyard.system.yml
Labels: ready-to-test

#2211 Update PROJECT in accordance with operator-sdk 1.23.0
  Makefile
  PROJECT
  scripts/kustomize/install_kustomize.sh
Labels: ready-to-test

#2258 Extract plugin discovery function registration
  pkg/discovery/network/calico.go
  pkg/discovery/network/canal.go
  pkg/discovery/network/kindnet.go
  pkg/discovery/network/network.go
  pkg/discovery/network/openshift4.go
  pkg/discovery/network/openshift4_test.go
  pkg/discovery/network/ovnkubernetes.go
  pkg/discovery/network/weavenet.go
Labels: ready-to-test

#2219 ABC-order variant analysis linting config
  .github/workflows/linting.yml
  .github/workflows/report.yml
Labels: automation, ready-to-test, blocked-on-rereview

#2260 Verify the Operator SDK checksum signature
  Makefile
  scripts/operator-sdk-signing-key.asc
  scripts/operator-sdk-signing-keyring.gpg
Labels: ready-to-test

#2239 Fix globalnet diagnose test
  config/rbac/submariner-diagnose/cluster_role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#2259 Remove ineffective `make build` in CodeQL jobs
  .github/workflows/linting.yml
  .github/workflows/report.yml
Labels: automation, ready-to-test
