Repository submariner-io/submariner-operator, pull requests merged in 2022-01, with the labels that each got.

#1728 Backport: Fix panic while running subctl gather
  pkg/subctl/cmd/gather/logs.go
Labels: ready-to-test

#1735 Rename clients from submariner and operator repo
  pkg/client/default_producer.go
  pkg/client/producer.go
  pkg/client/restconfig_producer.go
  pkg/deploy/broker.go
  pkg/subctl/cmd/deploybroker.go
Labels: ready-to-test

#1729 Backport: Fix invalid GlobalCidrRange when globalnet disabled (#1669)
  pkg/discovery/globalnet/globalnet.go
Labels: ready-to-test

#1712 Mount the Broker secret when available
  controllers/servicediscovery/servicediscovery_controller.go
  controllers/submariner/gateway_resources.go
  controllers/submariner/submariner_controller_test.go
  go.mod
  go.sum
  internal/restconfig/restconfig.go
Labels: ready-to-test

#1732 Add Cluster Role to Globalnet for services
  config/rbac/submariner-globalnet/cluster_role.yaml
Labels: ready-to-test

#1724 Store the PSK in a secret, and mount it
  api/submariner/v1alpha1/submariner_types.go
  config/crd/bases/submariner.io_submariners.yaml
  controllers/submariner/gateway_resources.go
  pkg/secret/ensure.go
  pkg/subctl/cmd/join.go
Labels: ready-to-test

#1738 Don't run some GHAs on drafts
  .github/workflows/cross.yml
  .github/workflows/e2e.yml
  .github/workflows/upgrade-e2e.yml
Labels: ready-to-test, test-draft

#1736 Update Submariner with the merged api module
  go.mod
  go.sum
Labels: ready-to-test

#1741 Use admiral's K8s zerolog integration
  controllers/servicediscovery/servicediscovery_controller_test.go
  controllers/submariner/submariner_controller_test.go
  go.mod
  go.sum
  main.go
  pkg/subctl/operator/common/operatorpod/ensure.go
Labels: ready-to-test

#1742 Sync the broker secret from the broker
  controllers/submariner/submariner_controller.go
  pkg/broker/ensure.go
  pkg/broker/rbac.go
Labels: ready-to-test

#1743 Move pkg/utils/crds to pkg/crd
  controllers/submariner/broker_controller.go
  controllers/submariner/submariner_controller.go
  main.go
  pkg/broker/ensure.go
  pkg/crd/crd_suite_test.go
  pkg/crd/updater.go
  pkg/crd/updater_test.go
  pkg/deploy/broker.go
  pkg/gateway/crds.go
  pkg/lighthouse/crds.go
  pkg/resource/create_or_update.go
  pkg/subctl/cmd/deploybroker.go
  pkg/subctl/operator/submarinerop/crds/ensure.go
  pkg/subctl/operator/submarinerop/ensure.go
  pkg/utils/crds/crdutils.go
  pkg/utils/createorupdate.go
  pkg/utils/createorupdate_test.go
Labels: ready-to-test

#1745 Avoid running tests on every PR edit
  .github/workflows/cross.yml
  .github/workflows/e2e.yml
  .github/workflows/upgrade-e2e.yml
Labels: ready-to-test

#1744 Determine the real "from version" for bundles
  Makefile
Labels: backport, ready-to-test

#1746 Determine the real "from version" for bundles
  Makefile
Labels: ready-to-test

#1760 Bump cloud-prepare
  go.mod
  go.sum
Labels: dependencies, ready-to-test

#1771 Update Operator to use version v0.12.0-m3
  api/submariner/v1alpha1/versions.go
  go.mod
  go.sum
Labels: ready-to-test

#1770 Use reporter.Interface in cmd/cloud
  pkg/subctl/cmd/cloud/aws/aws.go
  pkg/subctl/cmd/cloud/gcp/gcp.go
  pkg/subctl/cmd/cloud/generic/generic.go
  pkg/subctl/cmd/cloud/utils/reporter.go
Labels: ready-to-test

#1773 Remove unused GlobalCIDRConfigMap field from BrokerOptions
  pkg/deploy/broker.go
Labels: ready-to-test

#1776 Configure RBAC for Globalnet pods on OCP deployments
  config/rbac/submariner-globalnet/cluster_role.yaml
Labels: ready-to-test

#1777 Add test for oldest K8s version known to work
  .github/workflows/e2e-full.yml
Labels: automation, ready-to-test

#1783 Use AWS's default configuration handling
  go.mod
  go.sum
  pkg/subctl/cmd/cloud/aws/aws.go
Labels: ready-to-test

#1784 Delegate all AWS SDK use to cloud-prepare
  go.mod
  go.sum
  pkg/subctl/cmd/cloud/aws/aws.go
Labels: ready-to-test

#1786 cli.Status should output queued messages in order
  internal/cli/status.go
Labels: ready-to-test

#1788 Don't test Globalnet for every K8s version in FF
  .github/workflows/flake_finder.yml
Labels: automation, ready-to-test

#1787 Test K8s 1.23 in flake finder, not 1.19
  .github/workflows/flake_finder.yml
Labels: automation, ready-to-test

#1775 Deprecate colour codes, stop sending them to Submariner
  api/submariner/v1alpha1/submariner_types.go
  cmd/subctl/join.go
  go.mod
  go.sum
  pkg/deploy/submariner.go
  pkg/join/join.go
  pkg/join/options.go
  pkg/subctl/cmd/join.go
  scripts/kind-e2e/lib_operator_verify_subm.sh
Labels: ready-to-test

#1772 Refactor benchmark cmd
  .github/workflows/e2e-new-subctl.yml
  cmd/subctl/benchmark.go
  cmd/subctl/root.go
  internal/benchmark/latency.go
  internal/benchmark/throughput.go
  internal/constants/constants.go
  internal/exit/exit.go
  internal/restconfig/restconfig.go
Labels: ready-to-test

#1793 Check for fixup commits in PRs
  .github/workflows/linting.yml
Labels: ready-to-test

#1800 Replace utils.ExitOnError->exit.OnErrorWithMessage
  internal/restconfig/restconfig.go
  pkg/subctl/cmd/cloud/aws/aws.go
  pkg/subctl/cmd/cloud/cleanup/aws.go
  pkg/subctl/cmd/cloud/cleanup/gcp.go
  pkg/subctl/cmd/cloud/cleanup/generic.go
  pkg/subctl/cmd/cloud/gcp/gcp.go
  pkg/subctl/cmd/cloud/generic/generic.go
  pkg/subctl/cmd/cloud/prepare/aws.go
  pkg/subctl/cmd/cloud/prepare/gcp.go
  pkg/subctl/cmd/cloud/prepare/generic.go
  pkg/subctl/cmd/gather/gather.go
  pkg/subctl/cmd/show/networks.go
  pkg/subctl/cmd/show/versions.go
Labels: ready-to-test

#1795 Move verify to cmd/subctl
  .github/workflows/e2e-new-subctl.yml
  cmd/subctl/benchmark.go
  cmd/subctl/verify.go
Labels: ready-to-test

#1811 Clarify that crd.CreateOrUpdate handles embedded CRDs
  pkg/crd/updater.go
  pkg/crd/updater_test.go
  pkg/gateway/crds.go
  pkg/lighthouse/crds.go
  pkg/subctl/operator/submarinerop/crds/ensure.go
Labels: ready-to-test

#1813 Drop unnecessary Makefile && continuations
  Makefile
Labels: ready-to-test
