Repository submariner-io/submariner-operator, pull requests merged in 2022-08, with the labels that each got.

#2159 Use ENV vars instead of flags
  Makefile
  scripts/test/e2e.sh
  scripts/test/system.sh
Labels: ready-to-test

#2008 Reduce route-agent and gateway privileges
  config/rbac/submariner-gateway/role.yaml
  config/rbac/submariner-route-agent/cluster_role.yaml
  config/rbac/submariner-route-agent/role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test, release-note-needed

#2167 Require Go 1.18
  go.mod
  go.sum
Labels: ready-to-test

#2173 Set up Go 1.18 for the subctl consuming test
  .github/workflows/subctl-unit.yml
Labels: ready-to-test

#2181 Add Anchore Go dependency security scanning
  .github/workflows/linting.yml
  .github/workflows/report.yml
  .grype.yaml
Labels: ready-to-test

#2184 Only preload images used to deploy submariner
  Makefile
Labels: ready-to-test

#2186 Check the running operator version in e2e
  scripts/test/e2e.sh
Labels: ready-to-test, test-draft

#2180 Create all CRDs before initialising the scheme
  controllers/submariner/submariner_controller.go
  main.go
Labels: ready-to-test

#2185 Address overrides by component
  controllers/servicediscovery/servicediscovery_controller.go
  controllers/submariner/gateway_resources.go
  controllers/submariner/globalnet_resources.go
  controllers/submariner/np_syncer_resources.go
  controllers/submariner/route_agent_resources.go
Labels: backport, ready-to-test

#2189 Automated backport of #2185: Address overrides by component
  controllers/servicediscovery/servicediscovery_controller.go
  controllers/submariner/gateway_resources.go
  controllers/submariner/globalnet_resources.go
  controllers/submariner/np_syncer_resources.go
  controllers/submariner/route_agent_resources.go
Labels: ready-to-test, automated-backport

#2191 Remove `names.ImagePrefix/ImagePostfix`
  pkg/images/images.go
  pkg/names/names.go
Labels: ready-to-test

#2192 Set DNSPolicy to ClusterFirstWithHostNet
  controllers/submariner/gateway_resources.go
  controllers/submariner/globalnet_resources.go
  controllers/submariner/route_agent_resources.go
Labels: backport, ready-to-test

#2179 Update k8s, prometheus-operator & few other version
  Makefile
  config/crd/bases/submariner.io_brokers.yaml
  config/crd/bases/submariner.io_servicediscoveries.yaml
  config/crd/bases/submariner.io_submariners.yaml
  controllers/helpers/helpers.go
  go.mod
  go.sum
  pkg/crd/updater.go
  pkg/embeddedyamls/yamls.go
  pkg/metrics/service-monitor.go
Labels: ready-to-test

#2193 Use admiral's ReactingClient
  controllers/submariner/submariner_controller_test.go
  controllers/test/failing_client.go
  pkg/discovery/network/generic_test.go
Labels: ready-to-test

#2194 Remove client.Producer
  pkg/client/default_producer.go
  pkg/client/producer.go
  pkg/client/restconfig_producer.go
Labels: ready-to-test

#2198 Automated backport of #2192: Set DNSPolicy to ClusterFirstWithHostNet
  controllers/submariner/gateway_resources.go
  controllers/submariner/globalnet_resources.go
  controllers/submariner/route_agent_resources.go
Labels: ready-to-test, automated-backport

#2197 Automated backport of #2192: Set DNSPolicy to ClusterFirstWithHostNet
  controllers/submariner/gateway_resources.go
  controllers/submariner/globalnet_resources.go
  controllers/submariner/route_agent_resources.go
Labels: ready-to-test, automated-backport

#2201 Minimize GHA permissions
  .github/workflows/branch.yml
  .github/workflows/codeowners.yml
  .github/workflows/dependent-issues.yml
  .github/workflows/e2e-all-k8s.yml
  .github/workflows/e2e-full.yml
  .github/workflows/e2e.yml
  .github/workflows/flake_finder.yml
  .github/workflows/linting.yml
  .github/workflows/multiarch.yml
  .github/workflows/periodic.yml
  .github/workflows/prometheus.yml
  .github/workflows/release.yml
  .github/workflows/report.yml
  .github/workflows/subctl-unit.yml
  .github/workflows/system.yml
  .github/workflows/unit.yml
  .github/workflows/upgrade-e2e.yml
Labels: ready-to-test

#2199 Use current operator SDK-style metrics setup
  controllers/helpers/helpers.go
  controllers/metrics/metrics.go
  go.mod
  go.sum
  main.go
  pkg/metrics/metrics.go
  pkg/metrics/service-monitor.go
Labels: check-prometheus, ready-to-test

#2204 Remove use of obsolete operator-sdk
  go.mod
  go.sum
  main.go
  pkg/metrics/service-monitor.go
Labels: ready-to-test

#2212 Add CodeQL variant analysis scanning
  .github/workflows/linting.yml
  .github/workflows/report.yml
Labels: ready-to-test

#2208 Check GHA updates weekly
  .github/dependabot.yml
Labels: ready-to-test

#2209 Ensure we build the operator image for Prometheus
  .github/workflows/prometheus.yml
  controllers/metrics/metrics.go
Labels: automation, check-prometheus, ready-to-test

#2213 Remove unnecessary CodeQL SARIF upload
  .github/workflows/report.yml
Labels: ready-to-test

#2214 Restore gateway pod privileges
  config/rbac/submariner-gateway/role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#2216 Remove KubeClient in service discovery controller
  controllers/servicediscovery/cleanup.go
  controllers/servicediscovery/servicediscovery_controller.go
  controllers/servicediscovery/servicediscovery_controller_test.go
  controllers/servicediscovery/servicediscovery_suite_test.go
  go.mod
  go.sum
  main.go
Labels: ready-to-test

#2217 Rename SD Reconciler Client field to ScopedClient
  controllers/servicediscovery/cleanup.go
  controllers/servicediscovery/servicediscovery_controller.go
  controllers/servicediscovery/servicediscovery_suite_test.go
  main.go
Labels: ready-to-test

#2168 submariner-diagnose-role: add delete permissions for pods.
  config/rbac/submariner-diagnose/role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#2157 fix in diagnose cluster permissions: add getting deployments and namespaces
  config/rbac/submariner-diagnose/role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test
