Repository submariner-io/submariner-operator, pull requests merged in 2022-05, with the labels that each got.

#2037 Bump lighthouse version
  go.mod
  go.sum
Labels: ready-to-test

#2039 Point to submariner@feature-multi-active-gw for updated Endpoint CRD
  go.mod
  go.sum
Labels: ready-to-test

#2040 Bump Lighthouse to get latest E2E functionality
  go.mod
  go.sum
Labels: ready-to-test

#2038 Automated backport of #1961: Add JUnit report generation to "subctl verify"
  cmd/subctl/benchmark.go
  cmd/subctl/verify.go
  go.mod
  go.sum
  pkg/subctl/cmd/verify.go
Labels: ready-to-test

#2016 Switch strings.Title to cases.Title
  go.mod
  pkg/embeddedyamls/generators/yamls2go.go
Labels: ready-to-test

#2045 Adjust for Go 1.17
  api/submariner/v1alpha1/zz_generated.deepcopy.go
Labels: ready-to-test

#2047 Build packages, not files
  Makefile
Labels: ready-to-test

#2054 Bump markdown-link-check to the current tip
  .github/workflows/linting.yml
  .github/workflows/periodic.yml
Labels: ready-to-test

#2048 Refactor pkg/subctl/cmd/ -> pkg/cloud for RHOS
  pkg/cloud/cleanup/rhos.go
  pkg/cloud/prepare/rhos.go
  pkg/cloud/rhos/rhos.go
  pkg/subctl/cmd/cloud/cleanup/cleanup.go
  pkg/subctl/cmd/cloud/cleanup/rhos.go
  pkg/subctl/cmd/cloud/cloud.go
  pkg/subctl/cmd/cloud/prepare/aws.go
  pkg/subctl/cmd/cloud/prepare/prepare.go
  pkg/subctl/cmd/cloud/prepare/rhos.go
  pkg/subctl/cmd/cloud/rhos/rhos.go
Labels: ready-to-test

#2055 Update Lighthouse for nginx E2E on OpenShift fix
  go.mod
  go.sum
Labels: bug, ready-to-test

#2056 Revert "Refactor pkg/subctl/cmd/ -> pkg/cloud for RHOS"
  pkg/cloud/cleanup/rhos.go
  pkg/cloud/prepare/rhos.go
  pkg/cloud/rhos/rhos.go
  pkg/subctl/cmd/cloud/cleanup/cleanup.go
  pkg/subctl/cmd/cloud/cleanup/rhos.go
  pkg/subctl/cmd/cloud/cloud.go
  pkg/subctl/cmd/cloud/prepare/aws.go
  pkg/subctl/cmd/cloud/prepare/prepare.go
  pkg/subctl/cmd/cloud/prepare/rhos.go
  pkg/subctl/cmd/cloud/rhos/rhos.go
Labels: ready-to-test

#2058 Refactor pkg/subctl/cmd/ -> pkg/cloud for RHOS
  pkg/cloud/cleanup/rhos.go
  pkg/cloud/prepare/rhos.go
  pkg/cloud/rhos/rhos.go
  pkg/subctl/cmd/cloud/cleanup/cleanup.go
  pkg/subctl/cmd/cloud/cleanup/rhos.go
  pkg/subctl/cmd/cloud/cloud.go
  pkg/subctl/cmd/cloud/prepare/aws.go
  pkg/subctl/cmd/cloud/prepare/prepare.go
  pkg/subctl/cmd/cloud/prepare/rhos.go
  pkg/subctl/cmd/cloud/rhos/rhos.go
Labels: ready-to-test

#2052 Bump Lighthouse, drop the CoreDNS dependencies
  go.mod
  go.sum
Labels: ready-to-test

#2066 gather: Use libreswan as default if none specified
  internal/gather/cni.go
Labels: ready-to-test

#2073 Use == instead of Strings.Compare()
  cmd/subctl/benchmark.go
  cmd/subctl/verify.go
  pkg/subctl/cmd/benchmark.go
Labels: ready-to-test, maintenance

#2076 Require Go 1.17
  go.mod
  go.sum
Labels: ready-to-test

#2081 Remove pkg/resource
  pkg/crd/updater.go
  pkg/resource/create_or_update.go
Labels: ready-to-test

#2083 Automated backport of #2054: Bump markdown-link-check to the current tip
  .github/workflows/linting.yml
  .github/workflows/periodic.yml
Labels: ready-to-test, automated-backport

#2084 Automated backport of #2066: gather: Use libreswan as default if none specified
  pkg/subctl/cmd/gather/cni.go
Labels: automated-backport

#2085 Use Dependabot to update GHAs on release-0.12
  .github/dependabot.yml
Labels: ready-to-test, maintenance
