Repository submariner-io/submariner-operator, pull requests merged in 2023-05, with the labels that each got.

#2623 Bump github.com/docker/docker to v23.0.5
  go.mod
  go.sum
Labels: dependencies, security, ready-to-test

#2624 Automated backport of #2623: Bump github.com/docker/docker to v23.0.5
  go.mod
  go.sum
Labels: ready-to-test, release-note-needed, automated-backport

#2555 Embed Broker admin, client RBACs
  pkg/embeddedyamls/generators/yamls2go.go
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#2641 Remove unused Globalnet flags
  controllers/servicediscovery/servicediscovery_controller.go
  controllers/submariner/globalnet_resources.go
Labels: ready-to-test
