Repository submariner-io/submariner-operator, pull requests merged in 2023-10, with the labels that each got.

#2837 Add lease RBAC permissions for globalnet
  config/rbac/submariner-globalnet/role.yaml
  pkg/embeddedyamls/yamls.go
Labels: backport, ready-to-test

#2839 Use generic resource handling
  controllers/servicediscovery/cleanup.go
  controllers/servicediscovery/servicediscovery_controller.go
  controllers/submariner/cleanup.go
  controllers/submariner/submariner_controller.go
  controllers/test/driver.go
  go.mod
  go.sum
  pkg/crd/updater.go
Labels: ready-to-test

#2843 Automated backport of #2822: Create xtables.lock as a file if it doesn't already exist
  controllers/submariner/globalnet_resources.go
  controllers/submariner/route_agent_resources.go
Labels: automated-backport

#2846 Mount host path directories instead of sockets
  controllers/submariner/route_agent_resources.go
Labels: backport, ready-to-test

#2848 Automated backport of #2846: Mount host path directories instead of sockets
  controllers/submariner/route_agent_resources.go
Labels: ready-to-test, automated-backport

#2845 Automated backport of #2822: Create xtables.lock as a file if it doesn't already exist
  controllers/submariner/globalnet_resources.go
  controllers/submariner/route_agent_resources.go
Labels: ready-to-test, automated-backport

#2854 Allow halting (and restarting) pods on certificate errors
  api/v1alpha1/servicediscovery_types.go
  api/v1alpha1/submariner_types.go
  config/crd/bases/submariner.io_servicediscoveries.yaml
  config/crd/bases/submariner.io_submariners.yaml
  config/manifests/bases/submariner.clusterserviceversion.yaml
  controllers/servicediscovery/servicediscovery_controller.go
  controllers/submariner/gateway_resources.go
  controllers/submariner/servicediscovery_resources.go
  pkg/embeddedyamls/yamls.go
Labels: backport, ready-to-test

#2858 Automated backport of #2854: Allow halting (and restarting) pods on certificate errors
  api/v1alpha1/servicediscovery_types.go
  api/v1alpha1/submariner_types.go
  config/crd/bases/submariner.io_servicediscoveries.yaml
  config/crd/bases/submariner.io_submariners.yaml
  config/manifests/bases/submariner.clusterserviceversion.yaml
  controllers/servicediscovery/servicediscovery_controller.go
  controllers/submariner/gateway_resources.go
  controllers/submariner/servicediscovery_resources.go
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test, automated-backport

#2859 Remove release-notes files
  release-notes/20220216-flannel-cni.md
  release-notes/20220808-ra-gw-privs.md
  release-notes/20220908-metrics-proxy.md
Labels: ready-to-test

#2856 Enable Calico IPPools deletecollection in RouteAgent RBAC
  config/rbac/submariner-route-agent/cluster_role.yaml
  pkg/embeddedyamls/yamls.go
Labels: backport, ready-to-test, Calico

#2861 Backport: enable Calico IPPools deletecollection in RouteAgent RBAC
  config/rbac/submariner-route-agent/cluster_role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#2863 Make HaltOnCertificateError optional
  api/v1alpha1/submariner_types.go
  pkg/embeddedyamls/yamls.go
Labels: backport, ready-to-test

#2865 Automated backport of #2863: Make HaltOnCertificateError optional
  api/v1alpha1/submariner_types.go
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test, automated-backport
