Repository submariner-io/submariner-operator, pull requests merged in 2023-06, with the labels that each got.

#2665 Bump to Submariner v0.16.0-m0
  go.mod
  go.sum
Labels: ready-to-test

#2681 Update submariner to 0.13.6
  api/submariner/v1alpha1/versions.go
  go.mod
  go.sum
Labels: ready-to-test

#2675 Bump to Go 1.20
  go.mod
Labels: ready-to-test

#2683 Use Go 1.20 to test subctl
  .github/workflows/subctl-unit.yml
Labels: automation, ready-to-test

#2684 Disable depguard
  .golangci.yml
Labels: ready-to-test

#2682 Remove ValidImageNames
  pkg/names/names.go
Labels: technical-debt, ready-to-test

#2690 Register OVN-IC APIs
  pkg/embeddedyamls/generators/yamls2go.go
  pkg/embeddedyamls/yamls.go
  pkg/gateway/crds.go
Labels: ready-to-test

#2696 Disable dependabot PRs for parent-managed dependencies
  .github/dependabot.yml
Labels: ready-to-test

#2713 Include calico IPPools in routeagent clusterrole
  config/rbac/submariner-route-agent/cluster_role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test, release-note-needed, threat-model
