Repository submariner-io/submariner-operator, pull requests merged in 2023-11, with the labels that each got.

#2866 Update securejoin to fix GHSA-6xv5-86q9-7xr8
  go.mod
  go.sum
Labels: security, ready-to-test

#2878 Updates to fix grpc and docker CVEs
  go.mod
  go.sum
Labels: security, ready-to-test

#2881 Various updates to fix CVEs
  go.mod
  go.sum
Labels: security, ready-to-test

#2886 Override the ImageMagick license detection
  .lichen.yaml
Labels: ready-to-test

#2889 Revert "Create xtables.lock as a file if it doesn't already exist"
  controllers/submariner/globalnet_resources.go
  controllers/submariner/route_agent_resources.go
Labels: backport, ready-to-test

#2891 Automated backport of #2889: Revert "Create xtables.lock as a file if it doesn't already
  controllers/submariner/globalnet_resources.go
  controllers/submariner/route_agent_resources.go
Labels: ready-to-test, automated-backport

#2890 Automated backport of #2889: Revert "Create xtables.lock as a file if it doesn't already
  controllers/submariner/globalnet_resources.go
  controllers/submariner/route_agent_resources.go
Labels: ready-to-test, automated-backport

#2892 Switch from stale app to stale GHA
  .github/stale.yml
  .github/workflows/stale.yml
Labels: automation, ready-to-test
