Repository submariner-io/submariner-operator, pull requests merged in 2023-01, with the labels that each got.

#2426 Check subctl using the appropriate branch
  .github/workflows/subctl-unit.yml
Labels: automation, ready-to-test, maintenance

#2412 Remove replace for sigs.k8s.io/controller-runtime
  go.mod
  go.sum
Labels: ready-to-test

#2449 Automated backport of #2426: Check subctl using the appropriate branch
  .github/workflows/subctl-unit.yml
Labels: ready-to-test, automated-backport

#2451 Add operator access to list DaemonSets cluster-wide
  config/rbac/submariner-operator/cluster_role.yaml
  pkg/discovery/network/flannel.go
  pkg/embeddedyamls/yamls.go
Labels: backport, ready-to-test

#2452 Look up images by component
  pkg/images/images.go
Labels: ready-to-test

#2468 Remove unused BrokerCR name
  pkg/names/names.go
Labels: ready-to-test

#2473 Backport of subctl #518: Only call cloud prepare when it's needed
  pkg/subctl/cmd/cloud/prepare/aws.go
  pkg/subctl/cmd/cloud/prepare/gcp.go
  pkg/subctl/cmd/cloud/prepare/rhos.go
Labels: ready-to-test

#2480 Reduce dependabot frequency, target k8s bumps
  .github/dependabot.yml
Labels: ready-to-test, maintenance
