Repository submariner-io/submariner-operator, pull requests merged in 2023-02, with the labels that each got.

#2425 Run the upgrade job only on devel
  .github/workflows/upgrade-e2e.yml
Labels: automation, ready-to-test, maintenance

#2484 Implement "make build"
  Makefile
Labels: documentation, UX, ready-to-test

#2472 Use tool versions specified by Go dependencies
  Makefile
  go.mod
  go.sum
  tools.go
Labels: dependencies, ready-to-test

#2491 Add LH coredns permission to access Submariner resource
  config/rbac/lighthouse-coredns/cluster_role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#2470 Stop vendoring
  Makefile
Labels: ready-to-test, maintenance

#2496 Ignore prometheus-operator/pkg/apis/monitoring dependency
  .github/dependabot.yml
Labels: ready-to-test

#2512 Handle update conflict in Submariner controller
  controllers/submariner/submariner_controller.go
Labels: ready-to-test
