Repository submariner-io/submariner-operator, pull requests merged in 2023-09, with the labels that each got.

#2783 Don't check the gateway secrets
  scripts/test/system.sh
Labels: ready-to-test

#2784 Only release images on submariner-io
  .github/workflows/release.yml
Labels: automation, ready-to-test

#2771 Give permission to route-agent to access endpoints
  config/rbac/submariner-route-agent/cluster_role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#2785 Fix flannel CNI discovery
  pkg/discovery/network/flannel.go
Labels: ready-to-test

#2770 Improve podCIDR detection
  pkg/discovery/network/generic.go
  pkg/discovery/network/generic_test.go
Labels: ready-to-test

#2772 Mount both Openshift and non-openshift nbdb path to support upgrades
  controllers/submariner/route_agent_resources.go
Labels: ready-to-test

#2790 Remove OVN db discovery code from submariner-operator
  config/rbac/submariner-operator/cluster_role.yaml
  controllers/submariner/cleanup.go
  controllers/submariner/route_agent_resources.go
  controllers/submariner/submariner_controller.go
  pkg/discovery/network/openshift4.go
  pkg/discovery/network/ovnkubernetes.go
  pkg/discovery/network/ovnkubernetes_test.go
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#2795 Automated backport of #2769: Improve calico CNI detection
  pkg/discovery/network/calico.go
Labels: ready-to-test, release-note-needed, automated-backport

#2796 Automated backport of #2785: Fix flannel CNI discovery
  pkg/discovery/network/flannel.go
Labels: ready-to-test, release-note-needed, automated-backport

#2798 Ignore the controller version in generated files
  .github/workflows/linting.yml
Labels: ready-to-test

#2801 Configure dependabot for the release-0.16 branch
  .github/dependabot.yml
Labels: automation, ready-to-test

#2824 Wait for node readiness before starting route-agent
  controllers/submariner/route_agent_resources.go
Labels: backport, ready-to-test

#2825 Automated backport of #2824: Wait for node readiness before starting route-agent
  controllers/submariner/route_agent_resources.go
Labels: ready-to-test, automated-backport

#2823 Qualify the /lib/modules host path mount
  controllers/submariner/gateway_resources.go
Labels: ready-to-test

#2822 Create xtables.lock as a file if it doesn't already exist
  controllers/submariner/globalnet_resources.go
  controllers/submariner/route_agent_resources.go
Labels: ready-to-test
