Repository submariner-io/submariner-operator, pull requests merged in 2023-03, with the labels that each got.

#2528 Use pointer utility functions instead of temporaries
  controllers/servicediscovery/servicediscovery_controller.go
  pkg/metrics/service-monitor.go
Labels: technical-debt, ready-to-test

#2530 Add config field for nodePlacement
  api/v1alpha1/servicediscovery_types.go
  api/v1alpha1/submariner_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/submariner.io_servicediscoveries.yaml
  config/crd/bases/submariner.io_submariners.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#2533 Drop the spec.broker check
  scripts/test/system.sh
Labels: ready-to-test

#2543 Automated backport of #2491: Add LH coredns permission to access Submariner resource
  config/rbac/lighthouse-coredns/cluster_role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test, automated-backport

#2542 Bundle: restore the "replaces" calculation
  Makefile
  config/bundle/kustomization.template.yaml
Labels: ready-to-test

#2551 Add "serviceimports" get permission to submariner-diagnose role
  config/rbac/submariner-diagnose/cluster_role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#2550 Support for manual trigger of release image job
  .github/workflows/release.yml
Labels: ready-to-test

#2558 Automated backport of #2546: Bump tim-actions/get-pr-commits for Node.js update
  .github/workflows/linting.yml
Labels: ready-to-test, automated-backport

#2559 Automated backport of #2546: Bump tim-actions/get-pr-commits for Node.js update
  .github/workflows/linting.yml
Labels: ready-to-test, automated-backport

#2557 Add permissions on Globalnet status subresources
  config/rbac/submariner-globalnet/cluster_role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test
