Repository submariner-io/submariner-operator, pull requests merged in 2024-05, with the labels that each got.

#3048 Automated backport of #3042: Restrict route agent secret access
  config/rbac/submariner-route-agent/cluster_role.yaml
  config/rbac/submariner-route-agent/ovn_cluster_role.yaml
  config/rbac/submariner-route-agent/ovn_role_binding.yaml
  pkg/embeddedyamls/generators/yamls2go.go
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test, automated-backport

#3055 Bump golang.org/x/net from 0.17.0 to 0.23.0
  go.mod
  go.sum
Labels: security

#3059 Expand wildcards in RBAC yaml files
  config/broker/broker-admin/role.yaml
  config/broker/broker-client/role.yaml
  config/rbac/submariner-diagnose/cluster_role.yaml
  config/rbac/submariner-diagnose/role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#3058 Automated backport of #3049: Reduce RBAC permissions
  config/rbac/lighthouse-agent/cluster_role.yaml
  config/rbac/lighthouse-coredns/cluster_role.yaml
  config/rbac/submariner-gateway/cluster_role.yaml
  config/rbac/submariner-gateway/role.yaml
  config/rbac/submariner-globalnet/cluster_role.yaml
  config/rbac/submariner-globalnet/role.yaml
  config/rbac/submariner-operator/cluster_role.yaml
  config/rbac/submariner-operator/role.yaml
  config/rbac/submariner-route-agent/cluster_role.yaml
  config/rbac/submariner-route-agent/role.yaml
  pkg/embeddedyamls/yamls.go
  pkg/metrics/service-monitor.go
Labels: automated-backport

#3056 Adjust to IsMissingNamespaceErr API change
  go.mod
  go.sum
  pkg/metrics/service-monitor.go
Labels: ready-to-test

#3065 Add missing resources for diagnose
  config/broker/broker-client/role.yaml
  config/rbac/submariner-diagnose/role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#3064 Configure SAs to enforce mountable secrets
  config/rbac/lighthouse-agent/service_account.yaml
  config/rbac/lighthouse-coredns/service_account.yaml
  config/rbac/submariner-diagnose/service_account.yaml
  config/rbac/submariner-gateway/service_account.yaml
  config/rbac/submariner-globalnet/service_account.yaml
  config/rbac/submariner-operator/service_account.yaml
  config/rbac/submariner-route-agent/service_account.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#3067 Add more missing resources for diagnose and broker-client
  config/broker/broker-admin/role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#3066 Refactor 'globalCidr' global var to local
  pkg/discovery/globalnet/globalnet.go
Labels: ready-to-test

#3068 Remove automountServiceAccountToken from manager.yaml
  config/manager/manager.yaml
Labels: ready-to-test

#3077 Add RBAC access to finalizers for the operator role
  config/rbac/submariner-operator/role.yaml
  pkg/embeddedyamls/yamls.go
Labels: backport, ready-to-test

#3079 Automated backport of #3077: Add RBAC access to finalizers for the operator role
  config/rbac/submariner-operator/role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test, automated-backport

#3082 Automated backport of #3077: Add RBAC access to finalizers for the operator role
  config/rbac/submariner-operator/role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test, automated-backport

#3081 Automated backport of #3077: Add RBAC access to finalizers for the operator role
  config/rbac/submariner-operator/role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test, automated-backport

#3084 [0.17] Remove route-agent OVN secrets RBAC
  config/rbac/submariner-route-agent/cluster_role.yaml
  config/rbac/submariner-route-agent/ovn_cluster_role.yaml
  config/rbac/submariner-route-agent/ovn_role_binding.yaml
  pkg/embeddedyamls/generators/yamls2go.go
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#3083 Remove route-agent OVN secrets RBAC
  config/rbac/submariner-route-agent/cluster_role.yaml
  config/rbac/submariner-route-agent/ovn_cluster_role.yaml
  config/rbac/submariner-route-agent/ovn_role_binding.yaml
  pkg/embeddedyamls/generators/yamls2go.go
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#3070 Remove node update RBAC permission for route agent
  config/rbac/submariner-route-agent/cluster_role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#3069 Set subctl tests up with Go 1.22
  .github/workflows/subctl-unit.yml
Labels: ready-to-test

#3086 Automated backport of #3084: Remove route-agent OVN secrets RBAC
  config/rbac/submariner-route-agent/cluster_role.yaml
  config/rbac/submariner-route-agent/ovn_cluster_role.yaml
  config/rbac/submariner-route-agent/ovn_role_binding.yaml
  pkg/embeddedyamls/generators/yamls2go.go
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test, automated-backport

#3089 Automated backport of #3088: Use the GeneralClient when accessing operatorv1.DNS resources
  controllers/servicediscovery/servicediscovery_controller.go
  controllers/servicediscovery/servicediscovery_controller_test.go
  controllers/servicediscovery/servicediscovery_suite_test.go
Labels: ready-to-test, automated-backport

#3090 Automated backport of #3089: Use the GeneralClient when accessing operatorv1.DNS resources
  controllers/servicediscovery/servicediscovery_controller.go
  controllers/servicediscovery/servicediscovery_controller_test.go
  controllers/servicediscovery/servicediscovery_suite_test.go
Labels: ready-to-test, automated-backport

#3091 Adjust globalnet RBAC permissions
  config/rbac/submariner-globalnet/role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test
