Repository submariner-io/submariner-operator, pull requests merged in 2024-01, with the labels that each got.

#2926 Split tools dependencies into a separate module
  .github/dependabot.yml
  Makefile
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: ready-to-test

#2918 Change Go version in the 'Check subctl' job to 1.21
  .github/workflows/subctl-unit.yml
Labels: ready-to-test

#2895 Update K8s versions tested in E2E
  .github/workflows/e2e-all-k8s.yml
  .github/workflows/e2e-full.yml
  .github/workflows/flake_finder.yml
Labels: automation, ready-to-test, stale

#2932 Update crypto package to fix GHSA-45x7-px36-x8w8
  go.mod
  go.sum
Labels: security, ready-to-test

#2933 Fix concurrent map write crash in logIfChanged
  pkg/images/images.go
Labels: ready-to-test, release-note-needed

#2934 Automated backport of #2933: Fix concurrent map write crash in logIfChanged
  pkg/images/images.go
Labels: ready-to-test, automated-backport

#2942 Drop the Go 1.21.4 requirement in /tools
  tools/go.mod
Labels: ready-to-test

#2945 Use NewDynamicRESTMapper instead of NewDisoveryRESTMapper
  main.go
Labels: ready-to-test

#2946 Add Makefile.shipyard to .gitignore
  .gitignore
Labels: ready-to-test

#2949 Automated backport of #2946: Add Makefile.shipyard to .gitignore
  .gitignore
Labels: ready-to-test, automated-backport
