Repository submariner-io/submariner-operator, pull requests merged in 2024-08, with the labels that each got.

#3192 Automated backport of #3182: Bump github.com/docker/docker in /tools
  tools/go.mod
  tools/go.sum
Labels: automated-backport

#3193 Automated backport of #3182: Bump github.com/docker/docker in /tools
  tools/go.mod
  tools/go.sum
Labels: ready-to-test, automated-backport

#3194 Remove dependabot config for release 0.14
  .github/dependabot.yml
Labels: ready-to-test

#3200 Bump admiral to pull in K8s v0.31.0
  go.mod
  go.sum
Labels: ready-to-test

#3202 Bump shipyard and address golangci-lint v1.60.3 errors
  .golangci.yml
  controllers/submariner/gateway_resources.go
  controllers/submariner/loadbalancer_resources.go
  go.mod
  go.sum
  pkg/discovery/globalnet/globalnet.go
Labels: ready-to-test
