Repository submariner-io/submariner-operator, pull requests merged in 2024-02, with the labels that each got.

#2956 Enable the profiling endpoint
  main.go
Labels: ready-to-test

#2957 Add vthapar as code owner
  CODEOWNERS
  CODEOWNERS.in
Labels: ready-to-test

#2947 Bump default E2E K8s version from 1.28 to 1.29
  .github/workflows/e2e-all-k8s.yml
  .github/workflows/e2e-full.yml
Labels: ready-to-test

#2960 Automated backport of #2956: Enable the profiling endpoint
  main.go
Labels: ready-to-test, automated-backport

#2961 Add committers to release-related files
  CODEOWNERS
  CODEOWNERS.in
Labels: backport, ready-to-test

#2958 Add support for Calico IPPools get
  config/rbac/submariner-route-agent/cluster_role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test

#2963 [0.16] Backport code owner updates
  CODEOWNERS
  CODEOWNERS.in
Labels: ready-to-test

#2962 [0.17] Backport code owner updates
  CODEOWNERS
  CODEOWNERS.in
Labels: ready-to-test

#2964 [0.15] Backport code owner updates
  CODEOWNERS
  CODEOWNERS.in
Labels: ready-to-test

#2965 Automated backport of #2958: Add support for Calico IPPools get
  config/rbac/submariner-route-agent/cluster_role.yaml
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test, automated-backport

#2967 Ignore unused parameters
  controllers/submariner/submariner_controller.go
Labels: ready-to-test

#2969 Bump helm from 3.12.1 to 3.14.1 for CVE-2024-25620
  tools/go.mod
  tools/go.sum
Labels: security, ready-to-test

#2979 Ignore helm CVE-2024-25620
  .grype.yaml
Labels: ready-to-test
