Repository submariner-io/submariner-operator, pull requests merged in 2024-03, with the labels that each got.

#2980 Automated backport of #2979: Ignore helm CVE-2024-25620
  .grype.yaml
Labels: automated-backport

#2985 Add dependabot config for release-0.17
  .github/dependabot.yml
Labels: ready-to-test

#2976 Add subctl image name
  pkg/names/names.go
Labels: ready-to-test

#2989 Fix K8s versions tested in all-K8s GHA
  .github/workflows/e2e-all-k8s.yml
Labels: automation, ready-to-test, e2e-all-k8s

#2995 Automated backport of #2990: Only fail builds for high+ vulns
  .github/workflows/linting.yml
Labels: ready-to-test, automated-backport

#2993 Automated backport of #2990: Only fail builds for high+ vulns
  .github/workflows/linting.yml
Labels: ready-to-test, automated-backport

#2998 Automated backport of #2990: Only fail builds for high+ vulns
  .github/workflows/linting.yml
Labels: automated-backport

#3006 Fix linting errors with golangci-lint v1.57.1
  controllers/apply/apply.go
Labels: ready-to-test
