Repository submariner-io/submariner-operator, pull requests merged in 2025-02, with the labels that each got.

#3350 Update the bundle
  config/crd/bases/submariner.io_submariners.yaml
  config/manifests/bases/submariner.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
Labels: ready-to-test

#3355 Remove "placeholder" namespace in RBAC yaml
  config/broker/broker-admin/role_binding.yaml
  config/broker/broker-client/role_binding.yaml
  config/crd/bases/submariner.io_brokers.yaml
  config/crd/bases/submariner.io_servicediscoveries.yaml
  config/crd/bases/submariner.io_submariners.yaml
  config/rbac/lighthouse-agent/cluster_role_binding.yaml
  config/rbac/lighthouse-agent/ocp_cluster_role_binding.yaml
  config/rbac/lighthouse-coredns/cluster_role_binding.yaml
  config/rbac/lighthouse-coredns/ocp_cluster_role_binding.yaml
  config/rbac/submariner-diagnose/cluster_role_binding.yaml
  config/rbac/submariner-diagnose/ocp_cluster_role_binding.yaml
  config/rbac/submariner-gateway/cluster_role_binding.yaml
  config/rbac/submariner-gateway/ocp_cluster_role_binding.yaml
  config/rbac/submariner-gateway/role_binding.yaml
  config/rbac/submariner-globalnet/cluster_role_binding.yaml
  config/rbac/submariner-globalnet/ocp_cluster_role_binding.yaml
  config/rbac/submariner-operator/cluster_role_binding.yaml
  config/rbac/submariner-operator/ocp_cluster_role_binding.yaml
  config/rbac/submariner-route-agent/cluster_role_binding.yaml
  config/rbac/submariner-route-agent/ocp_cluster_role_binding.yaml
Labels: ready-to-test

#3354 Add 0.20 dependabot config; remove 0.15
  .github/dependabot.yml
Labels: ready-to-test

#3356 Automated backport of #3355: Remove "placeholder" namespace in RBAC yaml
  config/broker/broker-admin/role_binding.yaml
  config/broker/broker-client/role_binding.yaml
  config/crd/bases/submariner.io_brokers.yaml
  config/crd/bases/submariner.io_servicediscoveries.yaml
  config/crd/bases/submariner.io_submariners.yaml
  config/rbac/lighthouse-agent/cluster_role_binding.yaml
  config/rbac/lighthouse-agent/ocp_cluster_role_binding.yaml
  config/rbac/lighthouse-coredns/cluster_role_binding.yaml
  config/rbac/lighthouse-coredns/ocp_cluster_role_binding.yaml
  config/rbac/submariner-diagnose/cluster_role_binding.yaml
  config/rbac/submariner-diagnose/ocp_cluster_role_binding.yaml
  config/rbac/submariner-gateway/cluster_role_binding.yaml
  config/rbac/submariner-gateway/ocp_cluster_role_binding.yaml
  config/rbac/submariner-gateway/role_binding.yaml
  config/rbac/submariner-globalnet/cluster_role_binding.yaml
  config/rbac/submariner-globalnet/ocp_cluster_role_binding.yaml
  config/rbac/submariner-operator/cluster_role_binding.yaml
  config/rbac/submariner-operator/ocp_cluster_role_binding.yaml
  config/rbac/submariner-route-agent/cluster_role_binding.yaml
  config/rbac/submariner-route-agent/ocp_cluster_role_binding.yaml
Labels: ready-to-test, automated-backport

#3352 Update K8s versions tested in E2E
  .github/workflows/e2e-all-k8s.yml
  .github/workflows/e2e-full.yml
  .github/workflows/flake_finder.yml
Labels: ready-to-test, e2e-all-k8s

#3368 Check that the tested components are the new ones
  Makefile
Labels: ready-to-test

#3369 Remove remnants of the networkplugin syncer
  config/rbac/submariner-operator/cluster_role.yaml
  config/rbac/submariner-operator/role.yaml
  internal/controllers/submariner/migration_test.go
  internal/controllers/submariner/np_syncer_resources.go
  internal/controllers/submariner/submariner_controller.go
  pkg/embeddedyamls/yamls.go
Labels: ready-to-test
